-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Máy chủ: localhost
-- Thời gian đã tạo: Th6 05, 2025 lúc 05:33 AM
-- Phiên bản máy phục vụ: 10.4.28-MariaDB
-- Phiên bản PHP: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Cơ sở dữ liệu: `dataonline`
--
CREATE DATABASE IF NOT EXISTS `dataonline` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
USE `dataonline`;

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `chitietdonhang`
--

CREATE TABLE `chitietdonhang` (
  `iddonhang` int(11) NOT NULL,
  `idsp` int(11) NOT NULL,
  `soluong` int(11) NOT NULL,
  `gia` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `chitietdonhang`
--

INSERT INTO `chitietdonhang` (`iddonhang`, `idsp`, `soluong`, `gia`) VALUES
(265, 37, 1, '990000'),
(266, 109, 2, '19120000'),
(266, 107, 2, '12140000'),
(266, 108, 1, '14120000'),
(267, 106, 1, '12100000'),
(268, 106, 1, '12100000'),
(269, 52, 1, '6990000'),
(270, 109, 12, '19120000'),
(271, 106, 2, '12100000');

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `donhang`
--

CREATE TABLE `donhang` (
  `id` int(11) NOT NULL,
  `iduser` int(11) NOT NULL,
  `diachi` text NOT NULL,
  `sodienthoai` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `soluong` int(11) NOT NULL,
  `tongtien` varchar(255) NOT NULL,
  `trangthai` int(11) NOT NULL,
  `momo` text NOT NULL,
  `ngaydat` date NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `donhang`
--

INSERT INTO `donhang` (`id`, `iduser`, `diachi`, `sodienthoai`, `email`, `soluong`, `tongtien`, `trangthai`, `momo`, `ngaydat`) VALUES
(260, 56, 'TPvinh', '0865063204', 'baongoc@gmail.com', 2, '62240000', 0, '', '2025-04-29'),
(265, 54, 'Số 5 - Đường Duy Trinh-TP VINH', '0773321141', 'Onana@gmail.com', 1, '990000', 0, '', '2025-05-03'),
(266, 54, 'Kỳ Anh - Hà Tĩnh', '0773321141', 'Onana@gmail.com', 5, '76640000', 0, '', '2025-04-09'),
(267, 54, 'Sơn Đông - Trung Quốc', '0773321141', 'Onana@gmail.com', 1, '12100000', 0, '', '2025-05-03'),
(268, 54, 'Hà Tây - Hà Nội', '0773321141', 'Onana@gmail.com', 1, '12100000', 0, '', '2025-06-03'),
(269, 57, 'Trường ĐHSP KT Vinh', '0865063204', 'user9@gmail.com', 1, '6990000', 4, '', '2025-06-03'),
(270, 57, 'Hà Tĩnh', '0865063204', 'user9@gmail.com', 12, '229440000', 3, '', '2025-06-03'),
(271, 57, 'Số 1 văn đông - Văn Trung - TP Vinh', '0865063204', 'user9@gmail.com', 2, '24200000', 1, '', '2025-06-03');

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `khuyenmai`
--

CREATE TABLE `khuyenmai` (
  `id` int(11) NOT NULL,
  `url` varchar(250) NOT NULL,
  `thongtin` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `khuyenmai`
--

INSERT INTO `khuyenmai` (`id`, `url`, `thongtin`) VALUES
(1, 'https://kimlongcenter.com/upload/news/khuyen-mai-tet-2024.jpg', 'SIÊU SALE THÁNG 5 – MUA NGAY KẺO LỠ\r\n\r\nChỉ trong tuần này, cửa hàng mang đến chương trình ưu đãi cực hấp dẫn dành cho khách hàng:\r\n\r\nLaptop giảm giá đến 3.000.000 đồng, bảo hành chính hãng, tặng kèm nhiều phần quà hấp dẫn\r\n\r\nĐiện thoại thông minh ưu đãi lên tới 25%, hỗ trợ thu cũ đổi mới\r\n\r\nMiễn phí vận chuyển toàn quốc, giao hàng nhanh trong 24 giờ\r\n\r\nThanh toán linh hoạt, hỗ trợ trả góp 0% lãi suất\r\n\r\n'),
(4, 'https://didongthongminh.vn/upload_images/images/2022/01/15/1.png', 'TUẦN LỄ VÀNG – ƯU ĐÃI ĐẶC BIỆT CHO TÍN ĐỒ CÔNG NGHỆ\r\n\r\nCửa hàng đang triển khai chương trình khuyến mãi cực sốc dành riêng cho các dòng sản phẩm HOT:\r\n\r\nMua điện thoại tặng kèm tai nghe hoặc ốp lưng cao cấp\r\n\r\nGiảm thêm 500.000 đồng khi mua combo laptop + chuột không dây\r\n\r\nKhách hàng thân thiết được giảm thêm 5% toàn bộ đơn hàng\r\n\r\nĐăng ký tài khoản ngay để nhận mã giảm giá 100.000 đồng cho đơn đầu tiên\r\n\r\nNhanh tay săn ưu đãi – số lượng quà tặng và khuyến mãi có hạn!\r\n\r\n'),
(5, 'https://didongthongminh.vn/images/news/resize/anh-bai-viet-km-tet-1.jpg?version=1636963297', 'KHUYẾN MÃI MÙA HÈ - SĂN DEAL CỰC CHÁY\r\nMùa hè sôi động, giá giảm mạnh.\r\nĐiện thoại và laptop giảm giá đến 25%.\r\nTặng kèm phụ kiện chính hãng cho mỗi đơn hàng.\r\nGiao hàng nhanh, miễn phí toàn quốc.\r\nThời gian áp dụng: từ 1/6 đến 30/6.\r\n\r\nNhanh tay mua sắm để không bỏ lỡ ưu đãi hấp dẫn.\r\n\r\n'),
(6, 'https://hacom.vn/media/news/1904_Hacom1200x6753.jpg', 'MUA HÀNG LIỀN TAY – NHẬN NGAY QUÀ TẶNG\r\nKhi mua điện thoại hoặc laptop bất kỳ:\r\n Tặng 1 tai nghe không dây trị giá 250.000đ\r\n Giảm thêm 10% cho đơn hàng từ 5 triệu trở lên\r\n Hỗ trợ trả góp 0% lãi suất qua thẻ tín dụng\r\n\r\nChương trình áp dụng từ 15/6 đến hết 5/7.\r\nSố lượng quà tặng có hạn – nhanh tay lên bạn nhé!\r\n\r\n'),
(7, 'https://news.khangz.com/wp-content/uploads/2023/05/sale-6-3-750x418.jpg', 'SIÊU SALE THÁNG 6 – MUA NGAY KẺO LỠ!\nTuần lễ VÀNG ưu đãi – cơ hội săn deal KHỦNG chỉ có một lần trong tháng!\n\nLaptop giảm sốc đến 3.000.000 đồng – hàng chính hãng 100%, bảo hành dài lâu, tặng kèm phụ kiện cực chất, số lượng có hạn.\nĐiện thoại thông minh ưu đãi tới 25% – hỗ trợ thu cũ đổi mới, lên đời máy mới dễ dàng, tiết kiệm cực lớn.\nMiễn phí giao hàng toàn quốc – nhận hàng nhanh chóng trong 24 giờ, an tâm tuyệt đối.\nThanh toán linh hoạt, trả góp 0% lãi suất – không cần trả trước, mang ngay sản phẩm về tay.\n\nNhanh tay chốt đơn – ưu đãi chỉ áp dụng trong tuần này!\nĐừng bỏ lỡ cơ hội có 1-0-2 này!'),
(8, 'https://www.phucanh.vn/media/news/1906_heruclua-1.jpg', 'SIÊU SALE THÁNG 5 – CƠ HỘI VÀNG CHỈ TRONG TUẦN NÀY!\nTháng 5 rực lửa với loạt ưu đãi hấp dẫn, giúp bạn sở hữu công nghệ đỉnh cao với mức giá không thể tốt hơn!\n\n1. Laptop chính hãng – Giảm giá lên tới 3.000.000 đồng\nDành cho sinh viên, dân văn phòng hay dân công nghệ – tất cả đều có cơ hội sở hữu laptop chất lượng, cấu hình mạnh mẽ, bảo hành dài hạn. Ngoài ra, khách hàng còn nhận được nhiều phần quà giá trị như balo, chuột không dây, túi chống sốc,...\n\n2. Điện thoại thông minh – Ưu đãi lên đến 25%\nMuốn nâng cấp smartphone? Đây là lúc! Chương trình thu cũ đổi mới giúp bạn tiết kiệm thêm chi phí, dễ dàng sở hữu những mẫu điện thoại mới nhất, pin trâu, camera đẹp, hiệu năng vượt trội.\n\n3. Miễn phí giao hàng toàn quốc – Giao hàng nhanh trong 24 giờ\nDù bạn ở đâu, chúng tôi vẫn mang sản phẩm đến tận tay bạn miễn phí. Đặc biệt, khu vực nội thành sẽ được giao hàng chỉ trong vòng 24 giờ – nhanh chóng, tiện lợi, an tâm tuyệt đối.\n\n4. Hỗ trợ trả góp 0% lãi suất – Mua sắm dễ dàng, không lo tài chính\nKhông cần trả trước, không lo lãi suất – bạn có thể chia nhỏ số tiền thanh toán theo tháng mà vẫn nhận ngay sản phẩm về sử dụng. Thủ tục nhanh chóng, xét duyệt đơn giản.\n\nThời gian khuyến mãi: DUY NHẤT trong tuần này!\nSản phẩm số lượng có hạn – hãy nhanh tay để không bỏ lỡ cơ hội tuyệt vời này!'),
(9, 'https://cdnv2.tgdd.vn/mwg-static/dmx/News/Thumb/1573469/giang-sinh-sale-dam-giam-gia-smartphone-laptop-thumb638705685801950436.jpg', 'ĐẠI TIỆC CÔNG NGHỆ THÁNG 7 – GIÁ CỰC SỐC, ƯU ĐÃI KHÔNG PHANH!\r\n\r\nTháng 7 rực nắng, giảm giá rực hơn! Cửa hàng tung ra chương trình khuyến mãi lớn nhất mùa hè – chỉ kéo dài trong thời gian có hạn!\r\n\r\nLaptop thế hệ mới – giá “hạ nhiệt” tới 3 triệu đồng\r\nTrang bị ngay chiếc laptop hiệu suất cao, thiết kế mỏng nhẹ, cực phù hợp cho học tập, làm việc hay giải trí. Mỗi đơn hàng còn nhận quà tặng hấp dẫn như tai nghe, túi đựng laptop, và gói vệ sinh miễn phí trọn đời.\r\n\r\nSmartphone giảm giá sâu – đổi máy trong chớp mắt\r\nCác dòng điện thoại từ phổ thông đến cao cấp đều được giảm giá mạnh. Hỗ trợ đổi máy cũ lấy máy mới tại cửa hàng, kiểm tra nhanh, thu giá tốt. Đặc biệt: giảm thêm cho khách hàng thân thiết.\r\n\r\nGiao hàng siêu nhanh – miễn phí toàn quốc\r\nĐặt hàng online dễ dàng – chúng tôi giao đến tận tay bạn trên toàn quốc mà không mất phí. Với khu vực thành phố, hàng sẽ đến tay bạn trong vòng 24 giờ.\r\n\r\nTrả góp cực dễ – 0% lãi suất, duyệt trong ngày\r\nBạn chỉ cần CMND/CCCD – là có thể chia nhỏ khoản thanh toán, không lo áp lực tài chính. Áp dụng cho cả online và tại cửa hàng.'),
(10, 'https://hacom.vn/media/news/1904_Hacom1200x6753.jpg', 'MUA HÀNG LIỀN TAY – NHẬN NGAY QUÀ TẶNG\r\nKhi mua điện thoại hoặc laptop bất kỳ:\r\n Tặng 1 tai nghe không dây trị giá 250.000đ\r\n Giảm thêm 10% cho đơn hàng từ 5 triệu trở lên\r\n Hỗ trợ trả góp 0% lãi suất qua thẻ tín dụng\r\n\r\nChương trình áp dụng từ 15/6 đến hết 5/7.\r\nSố lượng quà tặng có hạn – nhanh tay lên bạn nhé!\r\n\r\n');

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `sanpham`
--

CREATE TABLE `sanpham` (
  `id` int(11) NOT NULL,
  `tensanpham` varchar(100) NOT NULL,
  `hinhanh` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `sanpham`
--

INSERT INTO `sanpham` (`id`, `tensanpham`, `hinhanh`) VALUES
(1, 'Trang chủ ', 'https://gaosachthanhhai.com/wp-content/uploads/2022/10/trang-chu.png'),
(2, 'Điện thoại ', 'https://image.plo.vn/w1000/Uploaded/2025/vrwqqxjwp/2024_09_01/cac-mau-iphone-tot-nhat-moi-thoi-dai-3747.jpeg.webp'),
(3, 'Laptop', 'https://cdn.tgdd.vn/Files/2021/03/04/1332362/1_800x450.jpg'),
(4, 'Thông tin', 'https://aeggroup.vn/wp-content/uploads/2020/09/icon-chat-luong.png'),
(5, 'Liên hệ ', 'https://png.pngtree.com/png-vector/20230316/ourmid/pngtree-admin-and-customer-service-job-vacancies-vector-png-image_6650726.png'),
(6, 'Đơn hàng', 'https://vanchuyentrungquoc247.com/wp-content/uploads/2015/04/icon-giao-hang.png');

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `sanphammoi`
--

CREATE TABLE `sanphammoi` (
  `id` int(11) NOT NULL,
  `tensp` varchar(250) NOT NULL,
  `giasp` varchar(100) NOT NULL,
  `hinhanh` text NOT NULL,
  `mota` text NOT NULL,
  `loai` int(2) NOT NULL,
  `linkvideo` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `sltonkho` int(3) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `sanphammoi`
--

INSERT INTO `sanphammoi` (`id`, `tensp`, `giasp`, `hinhanh`, `mota`, `loai`, `linkvideo`, `sltonkho`) VALUES
(1, 'iPhone 16 Pro Max 256GB ', '22500000', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-11-128gb.png', 'Đặc điểm nổi bật của iPhone 16 Pro Max 256GB | Chính hãng VN/A\r\nMàn hình Super Retina XDR 6,9 inch lớn hơn có viền mỏng hơn, đem đến cảm giác tuyệt vời khi cầm trên tay.\r\nĐiều khiển Camera - Chỉ cần trượt ngón tay để điều chỉnh camera giúp chụp ảnh hoặc quay video đẹp hoàn hảo và siêu nhanh.\r\niPhone 16 Pro Max có thiết kế titan cấp 5 với lớp hoàn thiện mới, tinh tế được xử lý bề mặt vi điểm.\r\niPhone 16 Pro Max được cài đặt sẵn hệ điều hành iOS 18, cho giao diện trực quan, dễ sử dụng và nhiều tính năng hữu ích.\r\n', 1, 'lr29fwPMpHE', 28),
(2, 'Laptop Gaming Acer Nitro V ANV15-51-58AN', '17000000', 'https://cdn.ankhang.vn/media/product/24565_laptop_gaming_acer_nitro_v_anv15_51_72vs_nh_qnasv_004_000.jpg', 'Đặc điểm nổi bật\r\nCPU Intel Core i5-13420H cân mọi tựa game từ AAA đến game Esport.\r\nGPU GeForce RTX 2050 mới nhất cho đồ họa cực đỉnh, chiến mọi tựa game với mức cài đặt cao.\r\nRAM 16 GB DDR5 5200Mhz, khả năng xử lý đa nhiệm và đa tác vụ của máy càng được tăng tốc tối đa.\r\nMàn hình 15.6 inch Full HD, tần số quét chuẩn chiến game 144Hz.\r\nỔ cứng 512GB PCIE rộng rãi, lưu mọi tựa game dễ dàng.\r\nLaptop Acer Nitro V mang một thiết kế gaming mạnh mẽ, màn hình 15.6” 144Hz FHD, cấu hình cân mọi tựa game với chip i5-13420H từ Intel. Bên cạnh đó, dòng laptop này còn được tích hợp GPU GeForce RTX 2050, RAM 16GB và lưu trữ khổng lồ với SSD 512GB tốc độ cao giúp mang lại trải nghiệm vượt trội cho người dùng.', 2, 'BwEk48Juyg0', 38),
(3, 'Samsung Galaxy Z Flip6 12GB 256GB', '21000000', 'https://down-vn.img.susercontent.com/file/vn-11134207-7ras8-m50ea44zggqg01', 'Đặc điểm nổi bật của Samsung Galaxy Z Flip6 12GB 256GB\r\nChip Snapdragon 8 Gen 3 8 nhân mang đến hiệu năng mạnh mẽ, cho phép bạn xử lý các tác vụ hàng ngày một cách mượt mà.\r\nMàn hình gập 6.7 inch Dynamic AMOLED 2X 120Hz mang đến trải nghiệm hình ảnh tuyệt vời, với độ phân giải cao.\r\nCamera sau 50MP + 12MP cho phép bạn chụp ảnh chất lượng cao, với độ chi tiết cao và màu sắc rực rỡ. \r\nPin dung lượng 4000 mAh cho phép bạn sử dụng điện thoại cả ngày dài mà không cần lo lắng về việc hết pin. \r\nSamsung Z Flip 6 sở hữu nhiều nâng cấp ấn tượng nhờ được trang bị chip Snapdragon 8 Gen 3 for Galaxy, RAM 12GB, mang lại hiệu năng mạnh mẽ cho đa nhiệm và chơi game. Camera chính 50MP của máy giúp cải thiện khả năng quay chụp, đặc biệt trong môi trường thiếu sáng. Cùng với đó là pin 4.000mAh, hỗ trợ sạc nhanh 25W, giúp kéo dài thời gian sử dụng của người dùng.', 1, 'YPFX9WEqATM', 19),
(4, 'Apple MacBook Air M2 2024 8CPU 256GB ', '18000000', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/i/m/image_1396_1.png', 'Đặc điểm nổi bật\r\nThiết kế sang trọng, lịch lãm - siêu mỏng 11.3mm, chỉ 1.24kg\r\nHiệu năng hàng đầu - Chip Apple m2, 8 nhân GPU, hỗ trợ tốt các phần mềm như Word, Axel, Adoble Premier\r\nĐa nhiệm mượt mà - Ram 16GB, SSD 256GB cho phép vừa làm việc, vừa nghe nhạc\r\nMàn hình sắc nét - Độ phân giải 2560 x 1664 cùng độ sáng 500 nits\r\nÂm thanh sống động - 4 loa tramg bị công nghệ dolby atmos và âm thanh đa chiều\r\nApple Macbook Air M2 2024 16GB 256GB thiết kế siêu mỏng 1.13cm, trang bị chip M2 8 nhân GPU, 16 nhân Neural Engine, RAM khủng 16GB, SSD 256GB, màn hình IPS Liquid Retina Display cùng hệ thống 4 loa cho trải nghiệm đỉnh cao.', 2, 'PvGD8B-qn3w', 17),
(5, 'Xiaomi 14T Pro 12GB 512GB', '14990000', 'https://cdn.tgdd.vn/Products/Images/42/329890/xiaomi-14t-pro-12gb-512gb-thumb-600x600.jpg', 'Đặc điểm nổi bật của Xiaomi 14T Pro 12GB 512GB\r\nHiệu năng Xiaomi 14T Pro 5G mạnh mẽ với chip MediaTek Dimensity 9300+ - Hiệu suất tối ưu cho các tác vụ nặng như chơi game, xử lý đồ họa và đa nhiệm mượt mà.\r\nMàn hình AMOLED 6.67 inch 144Hz siêu mượt - Trải nghiệm hình ảnh sắc nét, mọi thao tác trở nên mượt mà hơn, từ lướt web đến chơi game.\r\nPin 5.000mAh và sạc nhanh 120W - Điện thoại Xiaomi 14T Pro 5G giúp bạn sạc đầy chỉ trong vòng chưa đến 20 phút, đảm bảo thời lượng sử dụng lâu dài suốt cả ngày.\r\nHỗ trợ 5G và Wi-Fi 7 - Tốc độ kết nối siêu nhanh, giúp bạn trải nghiệm mượt mà từ xem video trực tuyến đến chơi game mà không lo bị gián đoạn.\r\nXiaomi 14T Pro 5G là một trong những mẫu smartphone cao cấp được mong đợi hàng đầu trong nửa cuối năm 2024. Sau nhiều tin đồn, Xiaomi chính thức ra mắt dòng sản phẩm vào ngày 26/9/2024 tại Berlin và ngày 27/9/2024 tại Việt Nam. Được kế thừa nhiều thành công từ dòng kế nhiệm, dòng kế nhiệm lần này được kỳ vọng là sẽ mang đến nhiều cải tiến đáng giá, đặc biệt là trong hiệu năng và thiết kế.', 1, 'CoBY6fb6710', 19),
(6, 'Laptop ASUS TUF Gaming F15 FX507ZC4', '15900000', 'https://anphat.com.vn/media/product/46655_rog_thumbnail_wkf_tuf_140w_recovered.jpg', 'Đặc điểm nổi bật\r\nBộ vi xử lý Intel Core i5-12500H cho hiệu năng mạnh mẽ để chơi game mượt mà, xử lý các tác vụ đa nhiệm và sáng tạo nội dung.\r\nMàn hình 15.6 inch với tần số quét 144Hz cho hình ảnh chuyển động mượt mà, giảm thiểu hiện tượng xé hình và giật lag, mang đến trải nghiệm chơi game tuyệt vời.\r\nHệ thống âm thanh 2 loa với công nghệ Dolby Atmos cho âm thanh sống động và chi tiết, mang đến trải nghiệm giải trí và chơi game tuyệt vời.\r\nỔ cứng SSD có dung lượng lưu trữ 512GB kèm tốc độ đọc/ghi dữ liệu cực cao, tải tựa game chỉ trong giây lát để bạn tận hưởng.\r\nLaptop Asus TUF Gaming F15 FX507ZC4-HN095W có ổ cứng SSD 512GB, với dung lượng RAM 16GB, giúp mang đến tốc độ truy cập thông tin ổn định và mượt mà hơn. Máy có màu sắc hiện đại, kích thước chỉ 35.4 x 25.1 x 2.24 ~ 2.49 cm không lo cồng kềnh khi mang theo. Bên cạnh đó, card đồ họa NVIDIA® GeForce RTX™ 3050, giúp nâng cao đồ họa sắc nét khi sử dụng. Bộ xử lý Intel® Core™ i5-12500H thế hệ 12, đáp ứng nhu cầu khác nhau của người dùng.', 2, 'Y4uaAkEh74I', 25),
(7, 'Laptop Gaming Acer Nitro 5 Tiger AN515 ', '15740000', 'https://file.hstatic.net/1000026716/file/gearvn-laptop-acer-nitro-5-tiger-an515-58-79uj-1_50597af38a6d497abe88d2097dbbbca5.png', 'Đặc điểm nổi bật\r\nChip Core i5-12500H cùng card rời RTX 3050 cho khả năng chiến các tựa game nặng, chỉnh sửa hình ảnh trên PTS, Render video ngắn mượt mà.\r\nRam 8GB+8GB, ổ cứng SSD 512GB mang đến tốc độ xử lý nhanh cùng đa nhiệm mượt mà.\r\nMàn hình 15.6 inch độ phân giải Full HD, mang lại chất lượng hiển thị sắc nét.\r\nCông nghệ âm thanh DTS X:Ultra Audio, Acer Purified, Acer TrueHarmony - mang lại trải nghiệm giải trí chân thật.\r\nBàn phím được tích hợp đèn - Thoả sức làm việc trong môi trường thiếu sáng', 2, 'xU-rB4Of1qA', 22),
(8, 'Laptop ASUS Vivobook 14 OLED A1405VA', '11100000', 'https://nguyengialaptop.com/wp-content/uploads/2024/06/Acer-Gaming-Nitro-5-Tiger-AN515-i7-12700h-600x600.jpg', 'Đặc điểm nổi bật\r\nThiết kế sang trọng, lịch lãm - siêu mỏng 11.3mm, chỉ 1.24kg\r\nĐặc điểm nổi bật\r\nTrang bị bộ vi xử lý Intel Core i5-13500H cung cấp hiệu suất xử lý đa nhiệm mạnh mẽ mọi tác vụ học tập, văn phòng\r\nMàn hình 14.0 inch 2.8K OLED mang lại độ sắc nét cao, độ tương phản tuyệt vời và màu sắc sống động, tạo ra trải nghiệm hình ảnh đỉnh cao cho người dùng\r\n16GB RAM giúp xử lý tác vụ nhanh chóng và mượt mà cùng ổ cứng SSD PCIe dung lượng lớn 512GB, giúp lưu trữ dữ liệu một cách nhanh chóng và an toàn\r\nTrang bị các tính năng tiện ích như webcam, Wifi, Bluetooth, cổng kết nối đa dạng để phục vụ nhu cầu làm việc và giải trí hàng ngày của người dùng\r\nLaptop Asus Vivobook 14 OLED A1405VA KM257W toả sáng với màn hình 14 inch rộng lớn, hiển thị với tấm nền OLED cao cấp có độ phân giải 2.8K dẫn đầu trong phân khúc. Laptop văn phòng Asus Vivobook 14 OLED A1405VA KM257W sở hữu loạt tiện ích thân thiện với người dùng cùng viên pin dung lượng lớn.', 2, 'f9tPJuXKtAg', 13),
(9, 'Xiaomi Redmi Note 13 Pro 8GB 256GB', '7500000', 'https://cdn.viettablet.com/images/detailed/59/xiaomi-redmi-note-13-pro-8-256_optimized.jpg', 'Đặc điểm nổi bật của Xiaomi Redmi Note 13 Pro 8GB 256GB\r\nThu hút mọi ánh nhìn với thiết kế đẹp mắt, mặt lưng và khung nhựa nhẹ được làm bóng.\r\nCông nghệ âm thanh Dolby Atmos - Trải nghiệm âm thanh sống động, chi tiết và mạnh mẽ.\r\nMàn hình lớn Full HD+ đi kèm tần số quét cao 120 Hz - Cho phép người dùng tận hưởng mọi chi tiết một cách rõ ràng.\r\nHiệu năng mạnh mẽ, phù hợp với nhu cầu sử dụng đa nhiệm của người dùng hiện nay với chip MediaTek Helio G99-Ultra.\r\nXiaomi Redmi Note 13 Pro 8GB 256GB sở hữu chip Helio G99-Ultra, RAM 8GB, ROM 256GB, bộ 3 camera 200MP – 8MP – 2MP quay phim FHD+, camera selfie 16MP, màn hình Xiaomi AMOLED 120Hz 6.67 inches, pin 5000mAh sạc nhanh 67W.\r\n\r\n', 1, 'NJehEAw6GCM', 19),
(10, 'Laptop Acer Aspire Lite AL16-51P-55N7 ', '18190000', 'https://mytholaptop.vn/wp-content/uploads/2023/08/NITRO-TIGER-I7.webp', 'Đặc điểm nổi bật\r\nSở hữu bộ vi xử lý Intel Core i5-1235U, đáp ứng tốt các tác vụ văn phòng và trải nghiệm đa phương tiện.\r\nVới 16GB RAM DDR5 và ổ SSD PCIe 512GB, máy mang lại hiệu suất vượt trội, khởi động nhanh và tải ứng dụng mượt mà.\r\nMàn hình 16 inch WUXGA cung cấp chất lượng hiển thị sắc nét và góc nhìn rộng, phù hợp cho các tác vụ văn phòng và giải trí.\r\nThiết kế gọn nhẹ, chỉ 1.8 kg giúp máy trở thành người bạn đồng hành lý tưởng cho di chuyển.\r\nLaptop Acer Aspire Lite AL16-51P-55N7 sở hữu màn hình 16 inch WUXGA, mang lại hình ảnh sắc nét và chất lượng cao, phù hợp cho cả công việc lẫn giải trí. Với bộ nhớ RAM DDR5 16GB, phiên bản laptop Acer Aspire này đảm bảo cung cấp hiệu suất mạnh mẽ cho các tác vụ đa nhiệm, giúp máy hoạt động mượt mà ngay cả khi xử lý nhiều ứng dụng cùng lúc. Cùng với đó là ổ cứng PCIe NVMe SSD 512GB không chỉ đảm bảo tốc độ truy cập dữ liệu nhanh mà còn cung cấp không gian lưu trữ rộng rãi.', 2, 'vSw0jGM6OEY', 40),
(11, 'OPPO Reno12 F 5G 8GB 256GB', '9680000', 'https://cdn.tgdd.vn/Products/Images/42/327190/oppo-reno12-f-5g-cam-thumbai-600x600.jpg', 'Đặc điểm nổi bật của OPPO Reno12 F 5G 8GB 256GB\r\nMàn hình rộng với độ phân giải Full HD+ cho hình ảnh sắc nét, màu sắc rực rỡ và độ tương phản cao, mang đến trải nghiệm xem phim, chơi game và đọc sách tuyệt vời.\r\nThiết kế mỏng nhẹ dễ dàng mang theo bên mình, đồng thời vẫn đảm bảo độ bền bỉ và chắc chắn.\r\nHỗ trợ sạc nhanh 45W - Sạc nhanh chóng và hiệu quả, giúp bạn tiết kiệm thời gian.\r\nHệ điều hành mới nhất mang đến nhiều tính năng mới và cải tiến.\r\nĐiện thoại OPPO Reno12 F 5G có dung lượng lưu trữ 8GB+256GB kết hợp chipset MediaTek D6300 đem đến sự ổn định để xử lý các tác vụ khác nhau. Với camera sau độ phân giải cao lên đến 50 MP và camera selfie 32MP, giúp đem đến hình ảnh sắc nét khi chụp và quay video. Dung lượng pin của điện thoại OPPO lớn 5.000 mAh sẽ cho phép đáp ứng các nhu cầu cá nhân như chơi game hay lướt web cả ngày. Bên cạnh đó, màn hình của điện thoại 6.67 inch, với độ làm mới 120 Hz, không lo bị giật lag khi sử dụng.', 1, 'o0x8eaU5xQw', 50),
(12, 'Laptop Dell Inspiron 15 3520 6R6NK', '12800000', 'https://img.websosanh.vn/v2/users/wss/images/laptop-dell-inspiron-15-3520-i/f11e2a7f7cae4.jpg', 'Đặc điểm nổi bật\r\nTrang bị bộ vi xử lý Intel Core i5-1235U, mang lại hiệu suất đáng tin cậy cho các tác vụ hàng ngày.\r\nVới 8GB RAM và ổ cứng 512GB, máy đáp ứng tốt nhu cầu lưu trữ và đa nhiệm của người dùng.\r\nMàn hình 15.6 inch FHD mang đến trải nghiệm xem đa phương tiện sống động.\r\nThiết kế vỏ nhựa màu đen tối giản, tạo cảm giác sang trọng và tinh tế.\r\nLaptop Dell Inspiron 15 3520 6R6NK sở hữu cấu hình đáp ứng tốt các nhu cầu làm việc văn phòng, học tập khi được trang bị con chip Intel Core i5 1235U, 8GB RAM cùng bộ nhớ trong 512GB. Màn hình 15.6 inch FHD của laptop còn được Dell tích hợp tần số quét nâng cao 120Hz để phục vụ tốt cho các cả hoạt động giải trí. Mẫu laptop Dell Inspiron này còn được tối giản số lượng cổng kết nối để đảm bảo được độ mỏng nhẹ và vẻ ngoài thanh lịch.', 2, 'W5kilT-rXro', 34),
(13, 'realme C55 6GB 128GB', '15890000', 'https://bimg.akulaku.net/goods/spu/4c46b8d486404f9293c1c94b15cbc6ac7127.jpeg', 'Đặc điểm nổi bật của realme C55 6GB 128GB\r\nKiểu dáng hiện đại với các cạnh viền vuông vức và camera được bố trí độc đáo\r\nThoả mãn niềm đam mê nhiếp ảnh với camera sau có độ phân giải lên đến 64MP\r\nDung lượng pin 5.000 mAh kèm sạc nhanh 33W giúp tiết kiệm thời gian sạc pin\r\nRAM 6GB giúp xử lý tốt đa tác vụ cùng ROM 128GB cho không gian lưu trữ lớn\r\nrealme C55 có màn hình 6.72 inch, full HD, độ phân giải sắc nét, bộ nhớ lưu trữ của điện thoại lớn 6GB+128GB. Thương hiệu này chạy hệ điều hành quen thuộc Android 12, các tác vụ nhanh nhạy và mượt mà hơn. Con chip set được trang bị là Mediatek Helio G88 giúp các tác vụ ổn định hơn trong thời gian dài.\r\n\r\n', 1, 'xv9VCtJmB1c', 42),
(14, 'Laptop HP 250 G9 AG2K7AT', '9900000', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/p/h/photo_2025-02-18_11-36-08.jpg', 'Đặc điểm nổi bật\r\nLaptop mạnh mẽ với vi xử lý Intel Core i5-1235U, mang đến hiệu suất vượt trội cho công việc và giải trí.\r\nVới 16GB RAM, máy có khả năng đa nhiệm mượt mà, giúp người dùng dễ dàng chạy nhiều ứng dụng cùng lúc.\r\nỔ cứng SSD 512GB PCIe cung cấp không gian lưu trữ rộng rãi và tốc độ truy xuất dữ liệu nhanh chóng.\r\nMàn hình 15.6 inch Full HD cho hình ảnh sắc nét và rõ ràng, rất phù hợp cho việc xem phim và làm việc.\r\nLaptop HP 250 G9 AG2K7AT mang lại khả năng đa nhiệm, truy xuất dữ liệu đỉnh cao và không gian lưu trữ lớn nhờ sở hữu RAM DDR4 16GB cùng bộ nhớ trong 512GB. Màn hình lớn 15.6 inch sử dụng tấm nền IPS chuẩn FullHD cho chất lượng hiển thị sắc nét, rực rỡ. Thiết kế vỏ nhựa tái chế thân thiện cùng trọng lượng chỉ 1.696kg mang đến sự linh hoạt. \r\n\r\n', 2, '8eVvFklnkiY', 26),
(15, 'Laptop LG Gram 2024 14Z90S-G.AH55A5', '16840000', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/t/e/text_d_i_4_17.png', 'Đặc điểm nổi bật\r\nLaptop có thiết kế mỏng nhẹ, lý tưởng cho những người thường xuyên di chuyển.\r\nTrang bị bộ vi xử lý Intel U5-125H, 16GB RAM và ổ cứng SSD 512GB PCIe có thể xử lý mượt mà các tác vụ văn phòng, học tập và giải trí nhẹ nhàng.\r\nMàn hình 14 inch độ phân giải 1920x1200 với tấm nền IPS và độ phủ màu DCI-P3 99% mang đến hình ảnh sắc nét, sống động và màu sắc chính xác.\r\nCài đặt sẵn hệ điều hành Windows 11 mới nhất, mang đến trải nghiệm sử dụng hiện đại và hiệu quả.\r\nLaptop LG Gram 2024 14Z90S-G.AH55A5 ấn tượng bởi hiệu quả xử lý ưu trội qua bộ chip Intel Core Ultra 5, kết hợp RAM chuẩn LPDRR5X 16GB cùng ổ cứng 512GB. Chiếc laptop LG này được trang bị màn hình IPS 14 inch phân giải cao với tốc độ làm mới 60Hz. Bên cạnh đó, mẫu laptop LG Gram 2024 này còn sở hữu thêm viên pin dung lượng đủ để chạy tác vụ trong nhiều giờ cùng đa dạng cổng giao tiếp phổ biến.', 2, 'Nx7fl5VeYnA', 15),
(16, 'Samsung Galaxy Plus WIFI 12GB 256GB', '8100000', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/t/a/tab-s9-fe-plus-bac_3_1_1.png', 'Đặc điểm nổi bật\r\nĐặc điểm nổi bật\r\nTrang bị màn hình 90Hz cực sắc nét, cho bạn đắm chìm vào những khung hình sống động.\r\nVới khung kim loại cao cấp và chỉ số đạt chuẩn IP68 - Cho độ bền bỉ và linh động cao.\r\nBộ vi xử lý Exynos 1380 - Cho khả năng vận hành mượt mà, trơn tru đa nhiệm các tác vụ.\r\nKết hợp với bút S - Pen siêu tiện lợi - Giúp người dùng tăng cường năng suất làm việc.', 1, 'SNlMQ-uERXY', 18),
(17, 'iPhone 13 512GB | Chính hãng VN/A', '26500000', 'https://taozinsaigon.com/files_upload/product/04_2022/thumbs/600_iphone_13_512gb_hong_moi_taozin.jpg', 'Đặc điểm nổi bật của iPhone 13 512GB | Chính hãng VN/A\r\nHiệu năng vượt trội - Chip Apple A15 Bionic mạnh mẽ, hỗ trợ mạng 5G tốc độ cao\r\nTrải nghiệm hiển thị sống động - Màn hình 6.1\" Super Retina XDR độ sáng cao, sắc nét\r\nBắt trọn từng khoảng khắc - Camera kép 12MP, hỗ trợ ổn định hình ảnh quang học\r\nTối ưu điện năng - Sạc nhanh 20 W, đầy 50% pin trong khoảng 30 phút\r\nĐiện thoại iPhone 13 512GB được nhiều khách hàng, người dùng yêu thích nhờ bộ nhớ cao, dung lượng pin lớn cùng tốc độ vượt trội giúp gia tăng khả năng xử lý của điện thoại một cách đáng kể, mang lại trải nghiệm ấn tượng cho người dùng.', 1, 'q_AS7ylOsUM', 33),
(18, 'Laptop Dell Vostro 3520 F0V0V256 ', '12000000', 'https://cdn2.cellphones.com.vn/200x/media/catalog/product/l/a/laptop-dell-vostro-3520-f0v0v256-thumbnails.png', 'Đặc điểm nổi bật\r\nCPU Intel Core i5-13420H cân mọi tựa game từ AAA đến game Esport.\r\nGPU GeForce RTX 2050 mới nhất cho đồ họa cực đỉnh, chiến mọi tựa game với mức cài đặt cao.\r\nRAM 16 GB DDR5 5200Mhz, khả năng xử lý đa nhiệm và đa tác vụ của máy càng được tăng tốc tối đa.\r\nMàn hình 15.6 inch Full HD, tần số quét chuẩn chiến game 144Hz.\r\nỔ cứng 512GB PCIE rộng rãi, lưu mọi tựa game dễ dàng.\r\nLaptop Acer Nitro V mang một thiết kế gaming mạnh mẽ, màn hình 15.6” 144Hz FHD, cấu hình cân mọi tựa game với chip i5-13420H từ Intel. Bên cạnh đó, dòng laptop này còn được tích hợp GPU GeForce RTX 2050, RAM 16GB và lưu trữ khổng lồ với SSD 512GB tốc độ cao giúp mang lại trải nghiệm vượt trội cho người dùng.', 2, 'ivCotQgrb2M', 24),
(19, 'ViVo Galaxy TT5 Flip6 12GB 256GB', '14300000', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/t/_/t_i_xu_ng_59_.png', 'Đặc điểm nổi bật của Samsung Galaxy Z Flip6 12GB 256GB\r\nChip Snapdragon 8 Gen 3 8 nhân mang đến hiệu năng mạnh mẽ, cho phép bạn xử lý các tác vụ hàng ngày một cách mượt mà.\r\nMàn hình gập 6.7 inch Dynamic AMOLED 2X 120Hz mang đến trải nghiệm hình ảnh tuyệt vời, với độ phân giải cao.\r\nCamera sau 50MP + 12MP cho phép bạn chụp ảnh chất lượng cao, với độ chi tiết cao và màu sắc rực rỡ. \r\nPin dung lượng 4000 mAh cho phép bạn sử dụng điện thoại cả ngày dài mà không cần lo lắng về việc hết pin. \r\nSamsung Z Flip 6 sở hữu nhiều nâng cấp ấn tượng nhờ được trang bị chip Snapdragon 8 Gen 3 for Galaxy, RAM 12GB, mang lại hiệu năng mạnh mẽ cho đa nhiệm và chơi game. Camera chính 50MP của máy giúp cải thiện khả năng quay chụp, đặc biệt trong môi trường thiếu sáng. Cùng với đó là pin 4.000mAh, hỗ trợ sạc nhanh 25W, giúp kéo dài thời gian sử dụng của người dùng.', 1, 'HBpnKl5mk7w', 34),
(20, 'Huawei Matebook X', '28400000', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/h/u/huawei-matebook-x_4_.jpg', 'Huawei Matebook X: Thiết kế gọn gàng, mỏng và hiệu năng cực tốt, mạnh mẽ\r\nLaptop Huawei Matebook X là con máy sở hữu hiệu năng cực tốt, đi kèm với thiết kế thông minh, gọn gàng và nhẹ nhàng giúp người dùng dễ dàng sử dụng di chuyển. Hãy cùng tham khảo bài viết bên dưới để hiểu rõ hơn về laptop Huawei Matebook X. \r\n\r\nThiết kế tỉ mỉ từ hợp kim nhôm chắc chắn và trọng lượng cực kỳ nhẹ nhàng\r\nVới chiếc laptop Huawei Matebook X được làm bằng một hợp kim nhôm - magie vô cùng tỉ mỉ. Với kích thước 304mm x 217mm x 14.6 mm kèm với hệ thống tản nhiệt không quạt khiến cho chiếc laptop trông mỏng mảnh và gọn gàng hơn rất nhiều. ', 2, 'gAM0MdIsBfU', 44),
(21, 'OPPO Find N3 16GB 512GB', '34990000', 'https://cdn.tgdd.vn/Products/Images/42/302953/oppo-find-n3-thumb-600x600.jpg', 'Đặc điểm nổi bật của OPPO Find N3 16GB 512GB\r\nBậc thầy thiết kế, siêu mỏng nhẹ - Mỏng chỉ 239g, nhẹ chỉ 5.8mm với nếp gấp tàng hình\r\nRực rõ mọi màn hình hiển thị - Kích thước lên đến 7.8mm, độ phân giải 2K+ cùng tần số quét 120Hz mượt mà\r\nBậc thầy nhiếp ảnh - 3 camera hàng đầu đến 64MP kết hợp cùng đa dạng chế độ chụp hoàn hảo\r\nNâng cao hiệu suất sử dụng - Chip MediaTek Dimensity 9200 5G mạnh mẽ cùng hàng loạt tính năng đa nhiệm thông tinh\r\nOPPO Find N3 nổi bật với màn hình chính OLED 7.82 inch hỗ trợ độ phân giải 2K+ và tần số quét 120Hz, mang đến trải nghiệm hình ảnh sắc nét và mượt mà. Bộ camera sau của Find N3 cũng khá ấn tượng với độ phân giải lên đến 64MP, kết hợp các công nghệ quay chụp tiên tiến, đáp ứng tốt nhu cầu nhiếp ảnh. Hiệu năng mạnh mẽ từ Snapdragon 8 Gen 2 cùng RAM 16GB trên máy cũng đảm bảo khả năng xử lý đa nhiệm vượt trội, thích hợp cho các tác vụ nặng hoặc chơi game đồ họa cao.', 1, 'VBS4ugY8nXA', 12),
(22, 'Laptop Gigabyte G6 MF-H2VN854KH', '21900000', 'https://bizweb.dktcdn.net/100/329/122/products/laptop-gaming-gigabyte-g6-mf-h2vn854kh-01-3063ff49-a1d2-4485-a75a-c061901c267b.jpg?v=1720089709460', 'Đặc điểm nổi bật\r\nTrang bị bộ vi xử lý Intel Core i7-13620H, mang lại hiệu suất cao cho các tác vụ nặng.\r\nVới 16GB RAM và ổ cứng 1TB PCIe, máy cung cấp không gian lưu trữ rộng rãi và đa nhiệm mượt mà.\r\nĐặc biệt, card đồ họa rời NVIDIA GeForce RTX 4050 với 6GB VRAM giúp xử lý đồ họa 3D và chơi game mượt mà.\r\nMàn hình 16.0 inch FHD+ với tần số quét 165Hz cho hình ảnh sắc nét và mượt mà, rất phù hợp cho game thủ và người làm đồ họa.\r\nLaptop Gigabyte G6 MF-H2VN854KH cung cấp hiệu năng đỉnh cao nhờ tích hợp chip Intel Core i7-13620H đi cùng RAM 16GB, ổ cứng chuẩn PCIe lên đến 1TB. Cùng với đó, chiếc laptop Gaming Gigabyte này còn sở hữu GPU rời GeForce RTX 4050 tiên tiến. Ngoài ra, màn hình FHD+ có kích thước 16 inch kèm theo tốc độ làm mới tối đa 165Hz cũng góp phần mang đến trải nghiệm trọn vẹn cho các game thủ. ', 2, '4346OpCjdxM', 22),
(23, 'Laptop Gigabyte MF F2VN333SH', '12730000', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/g/r/group_509_48_.png', 'Đặc điểm nổi bật\r\nCPU intel Core i5-12450H cho phép thực hiện các tác vụ hàng ngày nhanh chóng và mượt mà\r\nGPU GeForce RTX4050 cho hiệu suất tối thượng cho game thủ và nhà sáng tạo video\r\nMàn hình 15.6 inch IPS 144Hz mang đến màu sắc chơi game chân thực\r\nRAM 8GB cùng ổ cứng 512GB SSD hỗ trợ máy máy nhanh chóng, lưu trữ thoải mái\r\n', 2, '4346OpCjdxM', 32),
(24, 'Lrealme 13+ 5G 8GB 256GB', '8100000', 'https://mms.img.susercontent.com/sg-11134201-7rfi1-m48q4xwuvpfnad_tn', 'Đặc điểm nổi bật của realme 13+ 5G 8GB 256GB\r\nRealme 13+ 5G sử dụng bộ vi xử lý hiện đại, mang đến trải nghiệm mượt mà cho các tác vụ đa nhiệm và chơi game.\r\nMàn hình Full HD+ với tần số quét cao 120Hz cho hình ảnh mượt mà và sắc nét khi lướt web, xem video hoặc chơi game.\r\nHỗ trợ kết nối 5G giúp truy cập Internet nhanh chóng và ổn định, phù hợp cho nhu cầu công việc và giải trí trực tuyến.\r\nPin dung lượng lớn với công nghệ sạc nhanh, giúp người dùng có thể sử dụng lâu dài mà không lo lắng về việc sạc lại thường xuyên.\r\nrealme 13+ 5G chính hãng là sản phẩm ra mắt tiếp theo được người dùng săn đón rất nhiều hiện nay với đầy đủ các điểm mạnh vượt trội hơn so với đối thủ như chips xử lý vượt bậc, sạc nhanh lên đến 80W và có khả năng kháng nước tốt hơn so với thế hệ tiền nhiệm. Cùng khám phá chi tiết nhất về điện thoại trước thềm ra mắt để xem có nên mua điện thoại này ngay không nhé!', 1, '4346OpCjdxM', 42),
(25, 'Nothing Phone 2A 5G 8GB 128GB ', '9500000', 'https://news.siamphone.com/upload/news/nw52914/000_Nothing-Phone-(2a).jpg', 'Đặc điểm nổi bật của Nothing Phone 2A 5G 8GB 128GB - Chỉ có tại CellphoneS\r\nMàn hình 6.7 inch AMOLED, tần số quét 120Hz, hiển thị mượt mà, màu sắc rực rỡ.\r\nChip MediaTek Dimensity 7200 Pro mạnh mẽ với chip hàng đầu, xử lý đa nhiệm và game nặng mượt mà.\r\nCamera kép với cảm biến 50MP, chụp ảnh sắc nét, quay video 4K ấn tượng.\r\nPin 5000mAh, sạc nhanh - Dung lượng pin lớn, hỗ trợ sạc nhanh, đáp ứng nhu cầu dùng cả ngày dài.\r\nĐiện thoại Nothing Phone 2A nổi bật với thiết kế bắt mắt cùng màn hình Flexible AMOLED 6.7 inch phẳng cùng tần số quét 120Hz và độ sáng 1.300 nits. Bên trong, thiết bị được trang bị chip Dimensity 7200 Pro, hệ thống camera kép 50MP cùng viên pin 5000mAh. \r\n\r\n', 1, '4346OpCjdxM', 14),
(26, 'Laptop Acer Aspire 7 A715-76G-5806', '12190000', 'https://hoangkhue.vn/wp-content/uploads/2024/07/laptop-acer-aspire-7-a715-76g-5806-nhqmfsv002-i5-12450h-16gb-512gb-.png', 'Đặc điểm nổi bật\r\nMàn hình 15.6 inch Full HD cho không gian hiển thị tương đối rộng và rõ nét, màu sắc sống động\r\nCPU Intel Core i5 12450H cùng card RTX 3050 cân mọi tác vụ văn phòng, thoả sức chiến các tựa game yêu thích\r\nRAM 16 GB hỗ trợ nâng cấp tối đa 32 GB thoải mái thao tác với nhiều tabs Chrome mà không lo lag, giật\r\nỔ cứng SSD 512 GB rộng rãi giúp lưu trữ nhiều tệp tin, tài liệu nhanh chóng\r\nTần số quét 144 Hz giúp khung hình chuyển động trơn tru, hỗ trợ game thủ phản ứng nhanh chóng\r\nLaptop Acer Aspire 7 A715 76G 5806 được trang bị bộ vi xử lý i5 12450H cùng card màn hình rời 4GB RTX3050 và dung lượng RAM 16GB, ổ cứng SSD 512 GB. Máy sở hữu màn hình 15.6 inch FHD với tần số 144Hz. Ngoài ra, sản phẩm laptopAcer Aspire còn nổi bật với thiết kế tối giản, bền bỉ nhờ vỏ nhựa cùng nắp lưng kim loại cứng cáp.', 2, '4346OpCjdxM', 24),
(27, 'Nokia HMD 105 4G', '630000', 'https://cdn.tgdd.vn/Products/Images/42/329676/nokia-hmd-105-4g-pink-thumb-600x600.jpg', 'Đặc điểm nổi bật của Nokia HMD 105 4G\r\nNokia HMD 105 4G là chiếc điện thoại phổ thông hỗ trợ mạng 4G, cho phép bạn truy cập internet tốc độ cao nhanh chóng.\r\nMàn hình lớn 2.4 inches cũng giúp bạn dễ dàng đọc tin nhắn, xem danh bạ và sử dụng các ứng dụng.\r\nMáy được trang bị pin dung lượng 1450 mAh, giúp bạn thoải mái sử dụng điện thoại mà không lo hết pin.\r\nNokia HMD 105 4G thiết kế nhỏ gọn và bền bỉ, dễ dàng cầm nắm và mang theo bên mình.\r\nNokia HMD 105 4G là mẫu điện thoại phổ thông, sở hữu màn hình 2.4 inch QVGA, sử dụng chipset Unisoc T127 với sức mạnh cơ bản và bộ nhớ trong 128MB. Sản phẩm điện thoại phổ thông này trang bị pin 1450mAh, thiết kế siêu bền bỉ và sử dụng cổng sạc USB Type-C tiện lợi. Máy hỗ trợ mạng 4G, tích hợp jack tai nghe 3.5mm.', 1, '4346OpCjdxM', 34),
(28, 'Laptop MSI Modern 14 C12MO-660VN', '14200000', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/t/e/text_ng_n_1__2_26.png', 'Đặc điểm nổi bật\r\nThiết kế gọn nhẹ chỉ 1.4kg cơ động sẵn sàng theo bạn đi khắp nơi\r\nCPU Intel Core i5-1235U giải quyết nhanh gọn mọi tác vụ văn phòng\r\nRAM 16GB kết hợp ổ cứng 512GB SSD cho hiệu suất nhanh chóng, lưu trữ thoải mái\r\nMàn hình 14 inch Full HD cùng tấm nền IPS cho khả năng hiển thị sắc nét', 2, '4346OpCjdxM', 44),
(29, 'Nothing Phone 3A', '5890000', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/d/i/dien-thoai-nothing-phone-3a.png', 'Đặc điểm nổi bật của Nothing Phone 3A\r\nCamera chính 50MP + chống rung OIS, tích hợp AI Night Mode cho ảnh sắc nét trong mọi điều kiện ánh sáng.\r\nKích thước 6.77 inch, tần số quét 120Hz cho trải nghiệm vuốt chạm siêu mượt và màu sắc rực rỡ.\r\nHệ điều hành Nothing OS tối giản, mượt mà - Giao diện cực nhẹ, không app rác – cập nhật lâu dài, tối ưu hiệu năng cực kỳ mượt.\r\nPin trâu 5000mAh - Thoải mái dùng cả ngày dài, hỗ trợ sạc nhanh, sạc đầy 50% chỉ trong 30 phút.\r\nĐiện thoại Nothing Phone 3A có khả năng vận hành ổn định với bộ xử lý Qualcomm SM7635 Snapdragon 7s Gen 3 và dung lượng pin ấn tượng đến 5000 mAh. Sản phẩm còn có hệ thống 4 camera tiên tiến, hỗ trợ công cụ AI TrueLens 3. Thiết kế sang trọng và khả năng hiển thị trực quan của thiết bị cũng được người dùng đánh giá cao.', 1, '4346OpCjdxM', 15),
(30, 'Laptop MSI Katana 15 B13VFK-676VN', '19900000', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/g/r/group_509_30_.png', 'Đặc điểm nổi bật\r\nCPU Intel Core i7-13620H xử lý gọn gàng từng tác vụ nặng nhẹ\r\nGPU RTX 4060 cân mọi tựa game AAA với hiệu năng xử lý đồ họa đỉnh cao\r\n16GB RAM xử lý đa tác vụ thoải mái và mượt mà\r\nKhông gian lưu trũ khổng lồ lên đến 1TB SSD\r\nMàn hình 15.6 inch Full HD cùng tần số quét 144 Hz đảm bảo bắt kịp từng hành động của đối thủ\r\nBàn phím thiết kế 4-Zone RGB làm nổi bật không gian giải trí cho mọi game thủ', 2, '4346OpCjdxM', 25),
(31, 'Laptop Acer Aspire 3 Spin A3SP14-31PT-387Z', '17140000', 'https://cdn2.cellphones.com.vn/200x/media/catalog/product/t/e/text_d_i_1__3_13_1_1_1.png', 'Đặc điểm nổi bật\r\nLaptop có thiết kế mỏng nhẹ, lý tưởng cho những người thường xuyên di chuyển.\r\nTrang bị bộ vi xử lý Intel U5-125H, 16GB RAM và ổ cứng SSD 512GB PCIe có thể xử lý mượt mà các tác vụ văn phòng, học tập và giải trí nhẹ nhàng.\r\nMàn hình 14 inch độ phân giải 1920x1200 với tấm nền IPS và độ phủ màu DCI-P3 99% mang đến hình ảnh sắc nét, sống động và màu sắc chính xác.\r\nCài đặt sẵn hệ điều hành Windows 11 mới nhất, mang đến trải nghiệm sử dụng hiện đại và hiệu quả.\r\nLaptop LG Gram 2024 14Z90S-G.AH55A5 ấn tượng bởi hiệu quả xử lý ưu trội qua bộ chip Intel Core Ultra 5, kết hợp RAM chuẩn LPDRR5X 16GB cùng ổ cứng 512GB. Chiếc laptop LG này được trang bị màn hình IPS 14 inch phân giải cao với tốc độ làm mới 60Hz. Bên cạnh đó, mẫu laptop LG Gram 2024 này còn sở hữu thêm viên pin dung lượng đủ để chạy tác vụ trong nhiều giờ cùng đa dạng cổng giao tiếp phổ biến.', 2, '4346OpCjdxM', 34),
(32, 'TECNO SPARK 30 Pro 8GB 256GB Transformer', '9520000', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/d/i/dien-thoai-tecno-spark-30-pro-8gb-256gb.png', 'Đặc điểm nổi bật\r\nĐặc điểm nổi bật\r\nTrang bị màn hình 90Hz cực sắc nét, cho bạn đắm chìm vào những khung hình sống động.\r\nVới khung kim loại cao cấp và chỉ số đạt chuẩn IP68 - Cho độ bền bỉ và linh động cao.\r\nBộ vi xử lý Exynos 1380 - Cho khả năng vận hành mượt mà, trơn tru đa nhiệm các tác vụ.\r\nKết hợp với bút S - Pen siêu tiện lợi - Giúp người dùng tăng cường năng suất làm việc.', 1, '4346OpCjdxM', 44),
(33, 'iPhone 11 128GB | Chính hãng VN/A', '23500000', 'https://clickbuy.com.vn/uploads/images/2019/09/iphone-11-vang.png', 'Đặc điểm nổi bật của iPhone 11 128GB | Chính hãng VN/A\r\nMàu sắc phù hợp cá tính - 6 màu sắc bắt mắt để lựa chọn\r\nHiệu năng mượt mà, ổn định - Chip A13, RAM 4GB\r\nBắt trọn khung hình - Camera kép hỗ trợ góc rộng, chế độ Night Mode\r\nYên tâm sử dụng - Kháng nước, kháng bụi IP68, kính cường lực Gorilla Glass\r\niPhone 11 128GB giá bao nhiêu ở thời điểm hiện tại, có vừa túi tiền người mua hay không? Với cấu hình, thiết kế, hiệu năng được đánh giá cao, có thể thấy sản phẩm đến từ nhà Táo này là sự lựa chọn tối ưu trong tầm giá.', 1, '4346OpCjdxM', 16),
(34, 'Laptop MSI Modern 15 B7M-238VN', '13200000', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/t/e/text_ng_n_-_2023-06-19t173614.213.png', 'Đặc điểm nổi bật\r\nTrang bị màn hình viền siêu mỏng, trọng lượng chị 1.75kg thích hợp mang theo bên mình\r\nCPU R7 7730U giúp bạn dễ dàng xử lý tốt các tác vụ văn phòng cùng chỉnh ảnh nhẹ\r\nMàn hình 15.6 inch Full HD giúp chất lượng hình ảnh hiển thị tốt và chân thật\r\nTrang bị nhiều cổng kết nối giúp quá trình xuất/nhập dữ liệu trở nên dễ dàng, nhanh chóng\r\nRAM 16GB cùng ổ cứng SSD 512GB giúp lưu trữ dữ liệu tốt nhưng không bị lag trong quá trình sử dụng\r\n', 2, '4346OpCjdxM', 26),
(35, 'Infinix Hot 40i 8GB 256GB', '6040000', 'https://down-vn.img.susercontent.com/file/vn-11134207-7ras8-m3vxxntwdjn9fb', 'Đặc điểm nổi bật của Infinix Hot 40i 8GB 256GB\r\nChip xử lý game mạnh mẽ Unisoc T606 - Đem lại trải nghiệm mọi ứng dụng một cách mượt mà và không bị gián đoạn.\r\nMàn rộng 6,56 inch cùng tần số quét 90Hz cho phép hiển thị hình ảnh sắc nét đến từng chi tiết nhỏ trên màn hình.\r\nTạm biệt nỗi lo pin yếu với dung lượng pin lên đến 5000mAh cùng công nghệ sạc nhanh 18W.\r\nThiết kế nhẹ với mặt lưng tựa kính thời thượng và hiện đại, với kích thước lý tưởng để dễ dàng mang theo bên mình.\r\nĐiện thoại INFINIX HOT 40I sở hữu con chip Octa-Core Chipset cùng với bộ nhớ RAM 8GB, dung lượng lưu trữ 256GB ổn định. Điện thoại với màn hình 90Hz mượt mà cùng với dung lượng pin 5000mAh, hỗ trợ sạc nhanh công suất 18W. INFINIX HOT 40I còn được trang bị cụm camera chất lượng hỗ trợ AI với ống kính chính 50MP.', 1, '4346OpCjdxM', 27),
(36, 'Laptop Vaio FE 15 VWNC51527-BL', '13300000', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/t/e/text_ng_n_44__10.png', 'Laptop VAIO FE 15 VWNC51527-BL - Sang trọng cùng, mạnh mẽ\r\nLaptop VAIO FE 15 VWNC51527-BL sở hữu CPU Intel Core i5-1235U cùng với RAM 8GB đa nhiệm hỗ trợ người dùng duyệt web nhanh chóng. Thêm vào đó, vẻ ngoài sang trọng cũng là điểm sáng của dòng laptop Vaio này.\r\n\r\nDung lượng ổ cứng giúp lưu trữ rộng rãi cùng CPU mạnh mẽ\r\nChiếc laptop này sở hữu CPU mạnh mẽ giúp đáp ứng được mọi nhu cầu, tác vụ học tập và làm việc. RAM 8GB đa nhiệm còn giúp có thể duyệt web một cách nhanh chóng. Hệ điều hành Windows 11 hỗ trợ rất nhiều tính năng cho người dùng.', 2, '4346OpCjdxM', 12),
(37, 'Nokia 3210 4G', '990000', 'https://down-vn.img.susercontent.com/file/vn-11134207-7ras8-m5183rck4p14fc', 'Đặc điểm nổi bật của Nokia 3210 4G\r\nTrải nghiệm internet tốc độ cao với kết nối 4G, cho phép bạn lướt web, xem video và tải xuống nhanh chóng.\r\nThiết kế cổ điển với bàn phím vật lý quen thuộc, mang đến cảm giác hoài niệm và dễ sử dụng.\r\nCamera VGA: Cho phép bạn chụp ảnh và quay video đơn giản.\r\nMàn hình màu 2.4 inch: Hiển thị rõ ràng, dễ đọc.\r\nVỏ ngoài bằng polycarbonate bền bỉ, chống va đập và trầy xước.\r\nNokia 3210 4G được trang bị màn hình 2.4 inch QVGA, hỗ trợ kết nối 4G LTE kết hợp pin dung lượng 1450mAh cho thời gian thoại tới vài ngày. Bộ nhớ trong của máy là 128MB. Điện thoại có camera sau 2MP và chạy trên nền tảng hệ điều hành S30+.', 1, '4346OpCjdxM', 10),
(38, 'Laptop HP 240 G9 AG2J7AT', '5900000', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/g/r/group_659_2__2.png', 'Đặc điểm nổi bật\r\nTrang bị bộ vi xử lý Intel Core i5-1235U, mang lại hiệu suất mạnh mẽ cho các tác vụ văn phòng và giải trí.\r\nVới 16GB RAM, máy cho phép người dùng thực hiện đa nhiệm một cách mượt mà, lý tưởng cho công việc và học tập.\r\nỔ cứng 512GB PCIE cung cấp không gian lưu trữ rộng rãi và tốc độ truy xuất dữ liệu nhanh chóng.\r\nMàn hình 14.0 inch với độ phân giải FHD mang đến hình ảnh sắc nét và chi tiết, giúp người dùng dễ dàng theo dõi nội dung. \r\nLaptop HP 240 G9 AG2J7AT là sự kết hợp giữa hiệu năng mạnh mẽ của chip Intel i5-1235U và thiết kế gọn nhẹ, phù hợp cho học tập và làm việc. Sản phẩm laptop Core i5 được trang bị RAM 16GB và SSD 512GB giúp đa nhiệm và lưu trữ mượt mà. Màn hình 14 inch Full HD sắc nét với tấm nền IPS sắc nét. Máy hỗ trợ Bluetooth 5.3 cùng đầy đủ các cổng kết nối hiện đại, đáp ứng tốt nhu cầu sử dụng của học sinh, sinh viên và nhân viên văn phòng.', 2, 'C5cbiDj5S3g', 14),
(39, 'Laptop Acer Gaming Aspire 7 A715-76-53PJ', '11140000', 'https://m.media-amazon.com/images/I/61ZWZtsK+vL._AC_UF350,350_QL50_.jpg', 'Đặc điểm nổi bật\r\nCPU Intel Core i5-12450H dễ dàng xử lý mọi tác vụ làm việc học tập, làm việc thường ngày.\r\nRAM 16GB DDR4 cùng ổ cứng dung lượng 512GB PCIe NVMe SSD có tốc độ đọc ghi siêu cao, thời gian mở máy, truy cập tệp, copy tệp,... nhanh chóng.\r\nMàn hình 15.6 inch Full HD cho không gian trải nghiệm nội dung tương đối rộng rãi, màu sắc rõ nét.\r\nCông nghệ Acer ComfyView bảo vệ đôi mắt của bạn khỏi những tác động tiêu cực từ ánh sáng màn hình.\r\nLaptop Acer Gaming Aspire 7 A715-76-53PJ là chiếc laptop sở hữu cấu hình mạnh với bộ vi xử lý Intel Core thế hệ 12 và card đồ họa Intel UHD Graphics. Máy có màn hình 15.6 inch, độ phân giải Full HD (1920 x 1080), bộ nhớ RAM 16GB DDR4 và dung lượng lưu trữ SSD 512GB. Ngoài ra, máy còn được trang bị các cổng kết nối như HDMI, USB Type-C, USB 3.2 Gen 1 Type-A, RJ-45 và có khả năng chơi game tốt.', 2, 'jbEDcEGs86c', 14),
(40, 'Laptop Asus Vivobook 15 X1504ZA-NJ517W', '10120000', 'https://vn.store.asus.com/media/catalog/product/cache/74e490e088db727ef90851ac50e1fa20/x/1/x1504za-nj517w_vivobo.jpg', 'Đặc điểm nổi bật\r\nTrang bị vi xử lý Intel Core i5-1235U, cùng với card đồ họa tích hợp Intel Iris Xe Graphics, mang lại hiệu suất mạnh mẽ cho mọi nhu cầu từ công việc đến giải trí\r\nMàn hình FHD 15.6 inch với độ sáng 250 nits và độ phủ màu 45% NTSC, mang lại hình ảnh sắc nét và sống động\r\nCông nghệ âm thanh SonicMaster, cùng với loa tích hợp và micrô mảng, tạo ra trải nghiệm âm thanh vượt trội\r\nBảo mật với cảm biến vân tay tích hợp vào touchpad hỗ trợ mở máy chỉ với một chạm\r\nPin 42WHrs cho thời lượng sử dụng lâu dài, không bị gián đoạn trong công việc hoặc giải trí', 2, 'lkuVQjkfL5A', 17),
(41, 'Tecno Camon 40 Pro', '5900000', 'https://telefonika.com/wp-content/uploads/2025/02/Camon-40-Pro-600x600.jpg', 'Đặc điểm nổi bật của Tecno Camon 40 Pro\r\nPin lớn 5200 mAh với thiết kế mỏng nhẹ với độ bền cao và công nghệ xả chậm, cung cấp thời gian sử dụng lâu dài\r\nHiệu năng mạnh mẽ, chip Mediatek Helio G100 kết hợp RAM 8GB và ROM 256GB, đáp ứng mọi nhu cầu từ công việc đến giải trí\r\nCamera chất lượng cao với camera sau 50MP, 8MP góc rộng và camera trước 50MP, cho hình ảnh sắc nét và sống động\r\nTản nhiệt thông minh, tăng cường khả năng tản nhiệt lên 12,5% so với thế hệ trước, giúp thiết bị hoạt động ổn định\r\n Điện thoại Tecno Camon 40 Pro nổi bật với thiết kế hiện đại cùng mặt lưng độc đáo khi trang bị cụm ba vòng camera với camera chính lên đến 50MP sắc nét. Máy có kích thước mỏng nhẹ và dung lượng pin lớn 5100mAh hỗ trợ sạc nhanh 45W. Máy được trang bị chip Dimensity 7300, công nghệ mở rộng RAM và chạy hệ điều hành Android 15, mang lại hiệu năng mạnh mẽ và khả năng đa nhiệm mượt mà. \r\n\r\n', 1, 'PUP1WYmEXr0', 18),
(42, 'Laptop Masstel E140 Celeron', '8190000', 'https://cdn2.cellphones.com.vn/x/media/catalog/product/t/e/text_ng_n_8__4_54_1_1.png', 'Đặc điểm nổi bật\r\nTrang bị vi xử lý Intel Celeron N4120, RAM 4GB xử lý mượt mà các tác vụ văn phòng cơ bản, lướt web, xem phim giải trí.\r\nỔ cứng SSD 128GB cho tốc độ khởi động máy và mở ứng dụng nhanh chóng, đồng thời cung cấp không gian lưu trữ tài liệu, hình ảnh, video vừa đủ.\r\nMàn hình HD mang đến chất lượng hiển thị rõ ràng, màu sắc trung thực, đáp ứng tốt nhu cầu học tập, làm việc và giải trí.\r\nVới trọng lượng chỉ 1.39kg, dàng mang theo bên mình đến lớp học, văn phòng hay khi di chuyển.\r\nSở hữu mức giá phải chăng, là lựa chọn hợp lý cho học sinh, sinh viên, người mới đi làm hoặc những ai cần một chiếc laptop cơ bản với ngân sách tiết kiệm.\r\nMasstel E140 đáp ứng tốt tác vụ làm việc, học tập với con chip Intel Celeron N4120, card đồ họa Intel UHD Graphics kết hợp RAM 4 GB và SSD 128GB. Trải nghiệm học tập trực tuyến sắc nét với màn hình 14 inch cùng độ phân giải HD cùng camera độ phân giải HD tích hợp. Cùng với trọng lượng nhẹ chỉ 1.39kg giúp người dùng dễ dàng di chuyển, phục vụ học tập và làm việc.', 2, 'i18bahOxPyg', 19),
(43, 'OPPO Find X8 16GB 512GB', '5680000', 'https://chuyenphanphoi.vn/thumb/460x450/2/95/upload/product/662627910857.png', 'Đặc điểm nổi bật của OPPO Find X8 16GB 512GB\r\nOPPO Find X8 hữu chip Dimensity 9400 3nm với lõi Cortex-X925 sẽ đảm bảo xử lý mọi tác vụ một cách nhanh chóng.\r\nFind X8 sẽ được trang bị cụm 3 camera sau 50MP đảm bảo được sự đồng đều về chất lượng hình ảnh giữa các chế độ chụp.\r\nViên Pin 5630 mAh sẽ giúp dòng bạn kéo dài ra đáng kể thời gian dùng điện thoại, đáp ứng nhu cầu sử dụng hỗn hợp suốt cả ngày của người dùng.\r\nSau bao chờ đợi, OPPO đã thật sự trình làng người dùng với bộ đôi Flagship điện thoại OPPO Find X8 ra mắt tại thị trường Việt Nam vào tháng 11 hứa hẹn sẽ mang đến những cải tiến mới nhất, giá bán có phần dễ tiếp cận hơn so với các mẫu tiền nhiệm trước đây. Cùng với đó, trên dòng điện thoại mới còn được nâng cấp tác vụ AI mới nhất. Cùng khám phá chi tiết hơn về mẫu mới này ngay!', 1, 'EOdWW0C7uzE', 20),
(44, 'INOI A83 6GB 128GB', '4890000', 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lyllxu20x5ltab', 'Đặc điểm nổi bật của realme C55 6GB 128GB\r\nKiểu dáng hiện đại với các cạnh viền vuông vức và camera được bố trí độc đáo\r\nThoả mãn niềm đam mê nhiếp ảnh với camera sau có độ phân giải lên đến 64MP\r\nDung lượng pin 5.000 mAh kèm sạc nhanh 33W giúp tiết kiệm thời gian sạc pin\r\nRAM 6GB giúp xử lý tốt đa tác vụ cùng ROM 128GB cho không gian lưu trữ lớn\r\nrealme C55 có màn hình 6.72 inch, full HD, độ phân giải sắc nét, bộ nhớ lưu trữ của điện thoại lớn 6GB+128GB. Thương hiệu này chạy hệ điều hành quen thuộc Android 12, các tác vụ nhanh nhạy và mượt mà hơn. Con chip set được trang bị là Mediatek Helio G88 giúp các tác vụ ổn định hơn trong thời gian dài.\r\n\r\n', 1, 'Jnc8ZJoPA_Y', 22),
(45, 'Laptop ASUS Vivobook S 16 OLED M5606KA', '11900000', 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lz1f6zn3xajlc0', 'Đặc điểm nổi bật\r\nSở hữu thiết kế hiện đại, màu đen tinh tế, mang lại vẻ ngoài sang trọng và đẳng cấp.\r\nMáy được trang bị màn hình 16.0 inch OLED độ phân giải 3K, tần số quét 120Hz, cho hình ảnh sắc nét, màu sắc sống động và trải nghiệm thị giác vượt trội.\r\nHiệu năng mạnh mẽ với vi xử lý AMD Ryzen AI 7 350, RAM 24GB, và ổ cứng SSD 512GB PCIe, đáp ứng xuất sắc cả công việc nặng lẫn giải trí.\r\nSản phẩm được cài sẵn Windows 11 và Microsoft Office bản quyền, mang lại sự thuận tiện và sẵn sàng sử dụng ngay khi mở hộp.\r\nLaptop ASUS Vivobook S 16 OLED M5606KA-RI016WS RYZEN AI 7 mang đến hiệu năng mạnh mẽ nhờ vi xử lý AMD Ryzen AI 7 350, kết hợp RAM 24GB và SSD 512GB PCIe. Màn hình OLED 16\'\' độ phân giải 3K, tần số quét 120Hz giúp máy hiển thị hình ảnh khá chi tiết. Laptop còn được tích hợp sẵn Windows 11 Microsoft Office, sẵn sàng sử dụng ngay khi mở máy. ', 2, 'DI9ekBC3ImI', 24),
(46, 'Laptop ASUS ROG Strix G16 G614JU-N4450W', '36840000', 'https://laptopworld.vn/media/lib/09-10-2023/g16g6142023-4.png', 'Đặc điểm nổi bật\r\nBộ vi xử lý Intel Core i7-13650HX mạnh mẽ, máy cung cấp hiệu suất vượt trội cho đa nhiệm và ứng dụng nặng.\r\nRAM 32GB cùng ổ cứng 1TB PCIe giúp lưu trữ lớn và tốc độ truy xuất dữ liệu nhanh chóng.\r\nCard đồ họa NVIDIA GeForce RTX 4050 6GB mang lại trải nghiệm đồ họa mượt mà cho các tựa game hiện đại.\r\nMàn hình 16.0 inch WUXGA với tần số quét 240Hz cho hình ảnh sắc nét và chuyển động mượt mà.\r\nLaptop Asus ROG Strix G16 G614JU N4450W sở hữu bộ xử lý thế hệ thứ 13 của Intel mang tên Core i7-13650HX Processor 2.6GHz 14 lõi cùng VGA RTX 4050. Sản phẩm gồm RAM 16GB + 16GB, nâng cấp tối đa 32GB và bộ nhớ trong dung lượng 1TB chuẩn kết nối tốc độ cao M.2 PCIe. Màn hình lớn 16 inch tỷ lệ 16:10 mang đến chất lượng hiển thị đỉnh cao chuẩn QHD+ và siêu mượt mà với tốc độ làm tươi 240Hz. \r\n\r\n', 2, 'UcaIG1JGgek', 25),
(47, 'vivo Y18S 6GB 128GB', '9100000', 'https://cdn11.dienmaycholon.vn/filewebdmclnew/DMCL21/Picture/Apro/Apro_product_34316/vivo-y18s-6gb12_main_541.png', 'Đặc điểm nổi bật của vivo Y18S 6GB 128GB\r\nMàn hình LCD rộng 6.56 inch, độ sáng cao và độ phân giải sắc nét, mang đến trải nghiệm hình ảnh tuyệt vời\r\nĐược trang bị vi xử lý Mediatek Helio G85 và RAM 6GB, Y18S đảm bảo khả năng xử lý mượt mà và hiệu suất vượt trội.\r\nDung lượng lớn 5000mAh, mang đến thời gian sử dụng kéo dài trong suốt cả ngày mà không cần lo lắng về việc hết pin\r\nĐiện thoại vivo Y18S là sản phẩm có thiết kế bắt mắt và màn hình LCD rộng 6.56 inch, độ sáng cao và độ phân giải sắc nét, mang đến trải nghiệm hình ảnh tuyệt vời. Hệ thống camera sau với camera chính 50MP và 0.08MP cho phép bạn chụp ảnh chất lượng cao. Vi xử lý Mediatek Helio G85 và RAM 6GB đảm bảo hiệu suất mạnh mẽ và khả năng xử lý nhanh chóng. Bộ nhớ trong 128GB và khe cắm thẻ nhớ cho phép bạn lưu trữ nhiều dữ liệu. Y18S cũng có pin lớn 5000mAh với công nghệ sạc nhanh 15W, đảm bảo thời gian sử dụng dài và tiết kiệm thời gian sạc.', 1, 'bzYPq5Vc_pM', 17),
(48, 'Xiaomi Redmi Note 13 6GB 128GB', '6500000', 'https://cdn.viettablet.com/images/detailed/58/xiaomi-redmi-note-13-6-128_optimized.jpg', 'Đặc điểm nổi bật của Xiaomi Redmi Note 13 6GB 128GB\r\nBắt trọn khoảnh khắc - Cụm camera Redmi Note 13 đến 108MP mạnh mẽ cùng khả năng thu phóng 3x\r\nMàn hình đẳng cấp - Kích thước lớn 6.67\" AMOLED 120hz cuộn lướt mượt mà\r\nHiệu suất ổn định, đa nhiệm dễ dàng - Snapdragon 685 8 nhân cùng RAM 6GB\r\nTrải nghiệm Xiaomi Redmi Note 13 cả ngày không lo lắng - pin 5000mAh cùng sạc nhanh 33W\r\nVới Redmi Note 13, Xiaomi đã mang đến một trải nghiệm người dùng hoàn toàn mới. Chip Snapdragon 685 mạnh mẽ kết hợp cùng GPU Mali-G57 và RAM 6GB không chỉ giúp Xiaomi Note 13 chạy mượt mà các tác vụ hàng ngày mà còn đáp ứng tốt nhu cầu giải trí như chơi game đồ họa cao. Màn hình AMOLED 120Hz sắc nét, màu sắc sống động sẽ khiến bạn đắm chìm vào từng khung hình phim, hình ảnh.', 1, 'ioKBVJ6H_nc', 22),
(49, 'Apple MacBook Air M1 256GB 2020 ', '21760000', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/m/a/macbook_5_1.png', 'Đặc điểm nổi bật\r\nPhù hợp cho lập trình viên, thiết kế đồ họa 2D, dân văn phòng\r\nHiệu năng vượt trội - Cân mọi tác vụ từ word, exel đến chỉnh sửa ảnh trên các phần mềm như AI, PTS\r\nĐa nhiệm mượt mà - Ram 8GB cho phép vừa mở trình duyệt để tra cứu thông tin, vừa làm việc trên phần mềm\r\nTrang bị SSD 256GB - Cho thời gian khởi động nhanh chóng, tối ưu hoá thời gian load ứng dụng\r\nChất lượng hình ảnh sắc nét - Màn hình Retina cao cấp cùng công nghệ TrueTone cân bằng màu sắc\r\nThiết kế sang trọng - Nặng chỉ 1.29KG, độ dày 16.1mm. Tiện lợi mang theo mọi nơi', 2, 'xskiGsQJo70', 19),
(50, 'ViNubia Red Magic 9 ProVo Galaxy TT5 ', '11700000', 'https://www.vopmart.com/media/catalog/product/cache/fba01159e823484c6e3d091a338cccb0/n/x/nx769jp.jpg', 'Điện thoại Nubia Red Magic 9 Pro sở hữu con chip Qualcomm Snapdragon 8 Gen 3 cùng dung lượng RAM 12GB cho hiệu năng mạnh mẽ và chạy đa nhiệm ổn định. Sản phẩm được trang bị cụm 3 camera 50MP - 50MP - 2MP giúp chụp và quay phim với độ chi tiết cao. Viên pin dung lượng 6500 mAh thoải mái để giải trí và làm việc trên màn hình AMOLED 6.8 inch cả ngày dài.', 1, 'dcE1BkyBf7Q', 21),
(51, 'Laptop Gaming Acer Nitro V ANV15-51-57B2', '8400000', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/t/e/text_d_i_15__1_2.png', 'Đặc điểm nổi bật\r\nCPU Intel Core i5 3420H và card đồ họa RTX 4050 hỗ trợ thiết kế đồ họa, chỉnh sửa hình ảnh, video, render 2D, 3D,... dễ dàng.\r\nThoải mái chơi game, giải trí sống động trên màn hình 15.6 inch, độ phân giải FHD, tần số quét 144 Hz.\r\nRAM 16GB đa nhiệm giúp mở nhiều tab cùng lúc mà không lo lag, giật.\r\nỔ cứng 512 GB rộng rãi, hỗ trợ lưu trữ nhiều tài liệu, game mà không lo hết dung lượng.\r\nLaptop Gaming Acer Nitro V ANV15-51-57B2 mạnh mẽ ấn tượng với CPU Intel® Core™ i5 thế hệ 13 kết hợp cùng với card đồ họa NVIDIA® GeForce RTX™ 40 Series. Bên cạnh đó, màn hình 15.6\" FHD IPS 144Hz chất lượng chuẩn gaming và tản nhiệt mát lạnh. Đặc biệt, khả năng kết nối đa dạng, siêu tốc độ ấn tượng,... Tất cả sẽ giúp bạn có trải nghiệm mạnh mẽ, ấn tượng bất chấp mọi công việc.', 2, '629zGkbYjb8', 10),
(52, 'TECNO POVA 5 8GB 128GB', '6990000', 'https://cdn.mobilecity.vn/mobilecity-vn/images/2023/08/tecno-pova-5-x-free-fire-vang.jpg.webp', 'Đặc điểm nổi bật của TECNO POVA 5 8GB 128GB\r\nThiết kế mạnh mẽ, lạ mắt với mặt lưng phẳng đi kèm các họa tiết độc đáo.\r\nDung lượng pin cao 6000mAh - Sẵn sàng cho bạn chiến các tựa game mà không bị gián đoạn.\r\nMàn hình 6.78 inches, hỗ trợ độ phân giải 1080 x 2460 pixel - Chất lượng hình ảnh mượt mà, sắc nét.\r\nChip xử lý Helio G99 (6nm) - Cung cấp sức mạnh giúp bạn đáp ứng tốt mọi tác vụ.\r\nĐiện thoại Tecno Pova 5 hoạt động trên con chip MediaTek Helio G99 và bộ nhớ RAM 8GB cùng viên pin dung lượng 6000mAh hỗ trợ sạc nhanh công suất 45W. Vẻ ngoài máy với màn hình IPS LCD 6.78 inch tần số quét 120Hz hiển thị mượt mà. Cùng với đó cụm camera chính 50MP sẽ giúp điện thoại Tecno này sở hữu khả năng nhiếp ảnh ổn định.\r\n\r\n', 1, 'LtuJ7EQaCM8', 8),
(53, 'Masstel Izi 10 4G\r\n', '922000', 'https://masstel.vn/wp-content/uploads/2023/06/ava-S1.jpg', 'Đặc điểm nổi bật\r\nMasstel IZI 10 trang bị dung lượng pin lên đến 1000 mAh, đi cùng với đó là chip Unisoc UMS9117 và RAM 48 MB cho tốc độ phản hồi tốt. Đồng thời, chiếc điện thoại Masstel còn tích hợp thêm nhiều tính năng như khe cắm thẻ nhớ, đèn pin chiếu sáng, Radio FM,... tiện ích.', 1, 'UPK-40ZtJCQ', 13),
(54, 'Laptop LG Gram 2024 Pro 16Z90SP-K.AH75A5', '11230000', 'https://laptop88.vn/media/product/9229_mtsp_lg_gram_2024_copy.jpg', 'Đặc điểm nổi bật\r\nTrang bị bộ vi xử lý Intel Core U7-155H, 16GB RAM và ổ cứng SSD 512GB xử lý mượt mà các tác vụ học tập, văn phòng.\r\nMàn hình 16 inch độ phân giải 2880x1800 và độ phủ màu DCI-P3 100% mang đến hình ảnh sắc nét, sống động và màu sắc chính xác.\r\nKiểu dáng mỏng nhẹ ấn tượng với trọng lượng chỉ 1.19kg, thuận tiện cho việc di chuyển.\r\nSở hữu thiết kế sang trọng, vỏ ngoài siêu bền, mang đến vẻ đẹp cao cấp và chuyên nghiệp.\r\nLaptop LG Gram 2024 Pro 16Z90SP-K.AH75A5 mang lại hiệu suất xử lý vượt trội với CPU Intel Core Ultra 7 155H kết hợp thông số dung lượng bộ nhớ 16GB. Khả năng hiển thị cũng được nâng lên tối đa với màn hình OLED 16 inch với dải màu DCI-P3 99% và công nghệ chống chói. Bên cạnh đó, LG Gram 2024 Pro cũng được trang bị đầy đủ cổng giao tiếp với Wifi 6E tiên tiến.', 2, '6Z1mUDkr6l0', 13);
INSERT INTO `sanphammoi` (`id`, `tensp`, `giasp`, `hinhanh`, `mota`, `loai`, `linkvideo`, `sltonkho`) VALUES
(56, 'Tecno Pova 6 Neo 8GB 128GB', '6920000', 'https://cdn.viettelstore.vn/Images/Product/ProductImage/554314400.jpeg', 'Đặc điểm nổi bật của Tecno Pova 6 Neo 8GB 128GB\r\nPin 7000mAh cho phép sử dụng máy trong thời gian dài mà không cần lo lắng về việc hết pin.\r\nMàn hình 6.78 inch cho không gian rộng rãi để xem phim, chơi game và đọc sách.\r\nBộ vi xử lý 8 nhân cho hiệu năng mạnh mẽ để xử lý các tác vụ đa nhiệm, chơi game mượt mà và chỉnh sửa ảnh, video hiệu quả.\r\nHệ thống 3 camera sau với camera chính 50MP, camera góc siêu rộng 8MP và camera macro 2MP cho phép bạn chụp ảnh và quay video chất lượng cao trong mọi điều kiện ánh sáng.\r\nĐiện thoại Tenco Pova 6 Neo là dòng sản phẩm mới nhất đến từ nhà Tecno với khả năng giải trí cực đỉnh nhờ con chip MediaTek G99 Ultimate cùng dung lượng Ram lên đến 8GB cùng 128GB bộ nhớ trong. Ngoài ra sản phẩm cũng mang đến khả năng hiển thị vượt trội với màn hình 6.78 inch tần số quét 120Hz. Cụm camera chính lên đến 50MP hỗ trợ công nghệ AI cũng sẽ giúp bạn ghi lại mọi bức ảnh lung linh.\r\n\r\n', 1, 'Gm5AaW9JhFE', 16),
(57, 'Laptop ASUS TUF Gaming F15 FX507VU', '11190000', 'https://laptopworld.vn/media/lib/11-04-2023/340937541_6439254282753538_1136404090942215096_n.jpg', 'Đặc điểm nổi bật\r\nBộ xử lý Intel Core i7-13620H thế hệ thứ 13 mạnh mẽ cho mọi tác vụ\r\nMàn hình Full HD, tần số quét 144Hz hỗ trợ G-SYNC hỗ trợ chơi game sống động với tốc độ nhanh\r\nCard Geforce RTX 4050 cải thiện hiệu suất xử lý đồ họa và đảm bảo trải nghiệm chơi game tuyệt vời\r\nRAM 16GB cùng ổ cứng 512 GB SSD rút ngắn thời gian mở máy, khởi động ứng dụng\r\nLaptop Asus TUF Gaming F15 FX507VU-LP198W sở hữu thiết kế được đánh giá là khá nhỏ gọn với kích thước chỉ 35.4 x 25.1 x 2.24~2.49 cm và trọng lượng 2.20kg. Ngoài ra, dòng Asus Tuf này còn được trang bị bộ vi xử lý Intel Core i7-13620H, cung cấp hiệu suất cao với 10 lõi. Đi kèm theo đó là card đồ họa NVIDIA GeForce RTX 4050, RAM 16GB DDR5 có thể nâng cấp lên 32GB và bộ nhớ SSD 512GB PCIe 4.0 NVMe M.2, tạo nền tảng vững chắc cho trải nghiệm chơi game giải trí.', 2, '28RC93LLD', 15),
(58, 'OPPO A78 4G 8GB 256GB', '5630000', 'https://nghenhinvietnam.vn/uploads/global/quanghuy/2023/7/10/oppo/nghenhinvietnam_oppo_a78_4g_3.jpg', 'Đặc điểm nổi bật của OPPO A78 4G 8GB 256GB\r\nNâng cấp không gian giải trí cực sắc nét - Màn hình 6.43 inches, tần số quét 90hz\r\nHiệu năng ổn định, xử lí tác vụ mượt mà - Chip Qualcomm Snapdragon 680, RAM 8GB\r\nChụp ảnh thoả sức, sáng tạo hết mức - Camera 50 MP cùng nhiều chế độ xử lí thông minh\r\nPin trâu dùng thoải mái cả ngày - Dung lượng pin 5000 mAh cùng sạc nhanh siêu tốc\r\nLà mẫu điện thoại tầm trung đầu tiên được OPPO ra mắt trong năm 2023, OPPO A78 sở hữu một thiết kế bắt mắt cùng những cải tiến trong hiệu năng với vi xử lý Qualcomm Snapdragon 680 có khả năng hỗ trợ kết nối 4G, 8GB RAM ( mở rộng thêm 8GB), 256GB bộ nhớ và viên pin 5000mAh hỗ trợ công nghệ sạc siêu tốc 67W.', 1, 'Wion5OE5lM0', 17),
(59, 'Laptop Dell Vostro 3530 2H1TPI7', '10200000', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/l/a/laptop-dell-vostro-3520-f0v0v256-thumbnails.png', 'Đặc điểm nổi bật\r\nMáy được trang bị vi xử lý Intel Core i7-1355U, mang đến hiệu suất mạnh mẽ cho các tác vụ nặng và đa nhiệm.\r\nVới 16GB RAM và ổ cứng SSD 512GB PCIe, người dùng có không gian lưu trữ rộng rãi và tốc độ truy xuất dữ liệu nhanh chóng.\r\nMàn hình 15.6 inch Full HD cung cấp hình ảnh sắc nét và màu sắc sống động, lý tưởng cho công việc và giải trí.\r\nLaptop đi kèm với Free OS, cho phép người dùng tự cài đặt hệ điều hành theo nhu cầu cá nhân.\r\nLaptop Dell Vostro 3530 2H1TPI7 sở hữu cấu hình mạnh mẽ với Intel Core i7 thế hệ 13 cùng RAM 16GB DDR4, mang lại hiệu năng ấn tượng và khả năng đa nhiệm tốt. Máy được trang bị màn hình 15.6 inch Full HD LCD với tần số quét 120Hz, cho hình ảnh sắc nét và chuyển động mượt mà. Bên cạnh đó, lớp chống chói cũng giúp thế hệ laptop Dell Vostro này có thể làm việc dễ dàng trong mọi điều kiện ánh sáng. Máy có thiết kế vỏ carbon bền bỉ, trọng lượng nhẹ 1.66 kg và đầy đủ các cổng kết nối.', 2, 'UyEgJOFRYHI', 16),
(60, 'Nothing Phone CMF 1 8GB 256GB', '8910000', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQVEINv6VxXV7T6cwSGGL0ZkpgQzLtc-O3Ow&s', 'Đặc điểm nổi bật của Nothing Phone CMF 1 8GB 256GB\r\nMàn hình Super AMOLED 6.67 inch, cho chất lượng hình ảnh sắc nét, màu sắc sống động và độ tương phản cao.\r\nChip MediaTek Dimensity 7300 5G đáp ứng tốt các nhu cầu sử dụng hàng ngày như lướt web, xem video và chơi game nhẹ.\r\nCamera chính 50MP kết hợp với camera phụ, hỗ trợ chụp ảnh chi tiết và rõ ràng trong nhiều điều kiện ánh sáng.\r\nPin dung lượng lớn 5000mAh giúp điện thoại hoạt động cả ngày, không lo hết pin giữa chừng.', 1, '8dd1CUmU_V8', 19),
(61, 'Laptop MSI Gaming Katana AI B8VE-402VN', '9100000', 'https://bizweb.dktcdn.net/thumb/grande/100/329/122/products/laptop-gaming-msi-katana-a15-ai-b8ve-402vn.jpg?v=1706779257120', 'Đặc điểm nổi bật\r\nCấu hình mạnh mẽ với bộ vi xử lý AMD Ryzen 7-8845HS.\r\nRAM 16GB và ổ cứng SSD 512GB PCIe, đáp ứng nhu cầu hiệu suất và lưu trữ.\r\nCard đồ họa NVIDIA GeForce RTX 4050 6GB, đáp ứng tốt nhu cầu chơi game.\r\nMàn hình 15.6 inch Full HD 144Hz, mang lại trải nghiệm gaming mượt mà.\r\nThiết kế đẹp mắt với màu đen mạnh mẽ, phù hợp cho cả nhu cầu chơi game và sử dụng văn phòng.\r\nLaptop MSI Gaming Katana A15 AI B8VE-402VN sở hữu sức mạnh hiệu năng ấn tượng ngoài mong đợi với bộ xử lý AMD Ryzen R7-8845HS, cùng card đồ họa RTX 4050. Nâng tầm hiển thị với màn hình 15.6 inch, Full HD kết hợp tần số làm tươi lên đến 144Hz. Bên cạnh đó, MSI Gaming Katana A15 hỗ trợ gaming mạnh mẽ với hệ thống MSI Cooler Boost 5 cùng bàn phím 4-Zone RGB Gaming.', 2, 'o2SMFp8n2rI', 19),
(62, 'Laptop Gigabyte G6 KF-KH001\r\n', '18140000', 'https://bizweb.dktcdn.net/thumb/grande/100/329/122/products/laptop-gaming-gigabyte-g6-kf-h3vn853sh-1.jpg?v=1699515978140', 'Đặc điểm nổi bật\r\nTrang bị vi xử lý Intel Core i7-13620H mạnh mẽ, mang lại hiệu suất vượt trội cho các tác vụ nặng và chơi game.\r\nMáy sở hữu 16GB RAM và ổ cứng SSD 1TB PCIe, đảm bảo khả năng đa nhiệm mượt mà cùng không gian lưu trữ cực kỳ rộng rãi.\r\nCard đồ họa RTX 4060 8GB cho khả năng xử lý đồ họa xuất sắc, phù hợp với các game thủ và nhà sáng tạo nội dung chuyên nghiệp.\r\nMàn hình 16 inch FHD+ với tần số quét 165Hz mang đến hình ảnh mượt mà, sắc nét và trải nghiệm thị giác tuyệt vời, đặc biệt trong các tựa game tốc độ cao.\r\nLaptop Gigabyte G6 KF-9RC56KF0HJJANIVN000 trang bị CPU i7-13620H từ Intel kết hợp card đồ họa NVIDIA GeForce RTX 4060 8GB đem đến hiệu năng vượt trội. Laptop xử lý đa nhiệm nhanh chóng, mượt mà nhờ RAM 16GB, lưu trữ 1TB khổng lồ. Màn hình 16 inches chống chói với tần số 165Hz, độ phân giải FHD+ quan sát sắc nét, rộng rãi.', 2, 'abDeZXCfkWs', 11),
(63, 'iPhone 14 128GB | Chính hãng VN/A', '11120000', 'https://www.techone.vn/wp-content/uploads/2022/09/14-prm-den-1-02.jpg', 'Đặc điểm nổi bật của iPhone 14 128GB | Chính hãng VN/A\r\nTuyệt đỉnh thiết kế, tỉ mỉ từng đường nét - Nâng cấp toàn diện với kiểu dáng mới, nhiều lựa chọn màu sắc trẻ trung\r\nNâng tầm trải ngiệm giải trí đỉnh cao - Màn hình 6,1\"\" cùng tấm nền OLED có công nghệ Super Retina XDR cao cấp\r\nChụp ảnh chuyên nghiệp hơn - Cụm 2 camera 12 MP đi kèm nhiều chế độ và chức năng chụp hiện đại\r\nHiệu năng hàng đầu thế giới - Apple A15 Bionic 6 nhân xử lí nhanh, ổn định\r\niPhone 14 128GB sở hữu màn hình Retina XDR OLED kích thước 6.1 inch cùng độ sáng vượt trội lên đến 1200 nits. Máy cũng được trang bị camera kép 12 MP phía sau cùng cảm biến điểm ảnh lớn, đạt 1.9 micron giúp cải thiện khả năng chụp thiếu sáng. Mẫu iPhone 14 mới cũng mang trong mình con chip Apple A15 Bionic phiên bản 5 nhân mang lại hiệu suất vượt trội.', 1, 'KkqE9Uq_olI', 5),
(102, 'Laptop MSI Modern 14 C12MO-660VN', '17160000', 'https://bizweb.dktcdn.net/100/329/122/products/laptop-msi-modern-14-c12mo-660vn-jpg-v-1696089776037.jpg?v=1704297951273', 'Laptop MSI Modern 14 C12MO-660VN - Thoải mái lưu trữ, xử lý nhanh chóng \r\nLaptop MSI Modern 14 C12MO-660VN là chiếc laptop doanh nhân có nhiều cải tiến về sức mạnh và thiết kế. Cụ thể thiết bị được tích hợp chiếc CPU Intel core i5 và vỏ nhựa bền bỉ và rất nhẹ. Hãy xem đoạn mô tả sau đây để biết được thiết kế của laptop MSI Modern sang trọng như thế nào và khả năng xử lý dữ liệu ra sao nhé!\r\n\r\nTăng tốc độ xử lý, lưu trữ linh hoạt \r\nLaptop MSI Modern 14 C12MO-660VN được tích hợp chiếc Ram DDR4 3200 MHz giúp nâng cao hiệu suất hệ thống tổng thể, tăng tốc quá trình chạy ứng dụng. Thiết bị cũng cho phép đa nhiệm tốt hơn, hỗ trợ tốt cho quá trình thiết kế đồ họa, làm video,...', 2, '28RC93LLD', 16),
(103, 'Infinix Hot 40i 8GB 256GB', '9530000', 'https://admin.hoanghamobile.com/Uploads/2024/02/16/infinix-hot-40i-4.jpg', 'Đặc điểm nổi bật của Infinix Hot 40i 8GB 256GB\r\nĐiện thoại INFINIX HOT 40I sở hữu con chip Octa-Core Chipset cùng với bộ nhớ RAM 8GB, dung lượng lưu trữ 256GB ổn định. Điện thoại với màn hình 90Hz mượt mà cùng với dung lượng pin 5000mAh, hỗ trợ sạc nhanh công suất 18W. INFINIX HOT 40I còn được trang bị cụm camera chất lượng hỗ trợ AI với ống kính chính 50MP.', 1, 'Wion5OE5lM0', 12),
(104, 'Laptop Vaio FE 15 VWNC51527-BL', '11600000', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/t/e/text_ng_n_44__10.png', 'Laptop VAIO FE 15 VWNC51527-BL - Sang trọng cùng, mạnh mẽ\r\nLaptop VAIO FE 15 VWNC51527-BL sở hữu CPU Intel Core i5-1235U cùng với RAM 8GB đa nhiệm hỗ trợ người dùng duyệt web nhanh chóng. Thêm vào đó, vẻ ngoài sang trọng cũng là điểm sáng của dòng laptop Vaio này.\r\n\r\nDung lượng ổ cứng giúp lưu trữ rộng rãi cùng CPU mạnh mẽ\r\nChiếc laptop này sở hữu CPU mạnh mẽ giúp đáp ứng được mọi nhu cầu, tác vụ học tập và làm việc. RAM 8GB đa nhiệm còn giúp có thể duyệt web một cách nhanh chóng. Hệ điều hành Windows 11 hỗ trợ rất nhiều tính năng cho người dùng.', 2, 'UyEgJOFRYHI', 19),
(105, 'Xiaomi Redmi Note 13 Pro 5G ', '11910000', 'https://images-na.ssl-images-amazon.com/images/I/61asajlJrYL.jpg', 'Đặc điểm nổi bật của Xiaomi Redmi Note 13 Pro 5G 8GB 256GB\r\nĐiện thoại Xiaomi Redmi Note 13 Pro 5G 8GB 256GB tích hợp chip Snapdragon 7s Gen 2 (8 nhân) mạnh mẽ, xử lý tác vụ mượt mà, thúc đẩy hiệu năng toàn diện. Camera chính 200 MP của Note 13 Series cho phép ghi lại hình ảnh vô cùng sắc nét, mang đến trải nghiệm chụp ảnh chi tiết và sống động. Viên pin lớn 5100 mAh giúp Redmi Note 13 Pro hoạt động bền bỉ suốt cả ngày, giảm thiểu tình trạng sạc nhiều lần.', 1, '8dd1CUmU_V8', 11),
(106, 'PC CPS X ASUS Gaming Intel i3 Gen 12', '12100000', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/g/r/group_786_2_.png', 'Đặc điểm nổi bật\r\nPC CPS ASUS Gaming Intel i3 Gen 12 được trang bị vi xử lý Intel Core i3-12100F, đi kèm là Mainboard ASUS PRIME H610M-K D4, giúp máy hoạt động ổn định. Sản phẩm PC Gaming còn được gắn thêm dung lượng RAM 8GB và ổ cứng SSD 256GB. Ngoài ra, card đồ hoạ ASUS Dual Radeon RX 6500 XT OC 4GB DUAL-RX6500XT-O4G-V2 sẽ giúp hình ảnh đẹp hơn.', 2, 'o2SMFp8n2rI', 10),
(107, 'Màn hình Gaming LG UltraGear 24GS60F', '12140000', 'https://voz.vn/attachments/1745214903392-png.3015310/', 'Đặc điểm nổi bật\r\nMàn hình Gaming LG UltraGear 24GS60F-B 24 inch với độ phân giải 1920 x 1080 mang lại hình ảnh sắc nét, tỷ lệ khung hình 16:9 tiêu chuẩn rõ ràng khi dùng. Kích thước màn hình lên đến 24 inch kết hợp màu đen hiện đại, nâng cao trải nghiệm xem phim. Màn hình hỗ trợ gam màu rộng với sRGB 99% (Typ) và HDR10, tái tạo màu sắc trung thực hơn. Trang bị cổng DisplayPort và HDMI, sẽ hỗ trợ ghép nối cho nhiều sản phẩm khác nhau.', 2, 'abDeZXCfkWs', 14),
(108, 'iPhone 13 512GB | Chính hãng VN/A', '14120000', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/1/3/13_4_7_2_7.jpg', 'Đặc điểm nổi bật của iPhone 13 128GB | Chính hãng VN/A\r\niPhone 13 thường được trang bị chip A15 Bionic mạnh mẽ với 6 nhân CPU và 4 nhân GPU, cung cấp mức hiệu năng vượt trội, giúp xử lý nhanh chóng các tác vụ nặng. Màn hình Super Retina XDR 6.1 inch trên máy cũng được đánh giá cao khi mang tới hình ảnh sắc nét với độ sáng cao, tối ưu hóa trải nghiệm xem nội dung dưới mọi điều kiện ánh sáng. Chưa hết, iPhone13 còn sở hữu hệ thống camera kép 12MP với công nghệ ổn định hình ảnh quang học (OIS) cải thiện khả năng quay film, chụp hình, ngay cả khi đang ở trong môi trường ánh sáng yếu.\r\n\r\nCùng tìm hiểu chi tiết về thông số và giá bán iPhone 13 thường bao nhiêu qua nội dung chi tiết dưới đây!', 1, 'KkqE9Uq_olI', 6),
(109, 'Pc+Màn hình Gaming LG UltraGear 27GS50F', '19120000', 'https://product.hstatic.net/1000361104/product/1_ae034366ca1048b1a6dae72277b4ff0a.jpg', 'Đặc điểm nổi bật\r\nMàn hình gaming LG ULTRAGEAR 24GS50F-B 24 inch sở hữu màn hình FHD cùng tần số làm mới 180Hz, tốc độ phản hồi 1ms MBR ấn tượng. Màn hình với công nghệ AMD FreeSync hỗ trợ mang lại trải nghiệm hình ảnh mượt mà. Cùng với đó màn hình còn sở hữu công nghệ tối ưu chơi game như chế độ ổn định màu đen, bộ đếm FPS hay đồng bộ hành động.', 1, 'KkqE9Uq_olI', 12),
(110, 'Samsung Galaxy S25 Ultra 12GB 256GB', '31120000', 'https://www.didongmy.com/vnt_upload/product/01_2025/thumbs/600_crop_samsung-galaxy-s25-ultra-5g-512gb-chinh-hang-didongmy-thumb-600x600.jpg', 'Đặc điểm nổi bật của Samsung Galaxy S25 Ultra 12GB 256GB\r\nSamsung S25 Ultra mạnh mẽ với chip Snapdragon 8 Elite For Galaxy mới nhất, RAM 12GB và bộ nhớ trong 256GB-1TB. Hệ thống 3 camera sau chất lượng gồm camera chính 200MP, camera tele 50MP và camera góc siêu rộng 50MP. Thiết kế kính cường lực Corning Gorilla Armor 2 và khung viền Titanium, màn hình Dynamic AMOLED 6.9 inch. Điện thoại này còn có viên pin 5000mAh, hỗ trợ 5G và Galaxy AI ấn tượng, nâng cao trải nghiệm người dùng!', 1, 'urpieLXUaSY', 6);

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `user`
--

CREATE TABLE `user` (
  `id` int(11) NOT NULL,
  `email` varchar(250) NOT NULL,
  `pass` varchar(250) NOT NULL,
  `username` varchar(100) NOT NULL,
  `mobile` varchar(15) NOT NULL,
  `uid` text NOT NULL,
  `token` text NOT NULL,
  `status` int(2) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `user`
--

INSERT INTO `user` (`id`, `email`, `pass`, `username`, `mobile`, `uid`, `token`, `status`) VALUES
(26, 'namduchuong204@gmail.com', '12345678', 'nam', '0865063204', 'Ati1A4G3uUeP2zOoVTThSmHxYiG3', 'f7vBYeD9Tx6vAKmpOvayHZ:APA91bHxHCbCvHPs0d7I0F1lh8qutjvmvFs8j6gCzAoimlI3je3ZzATS8FK66l1A4kKvOBrWBdXLbvYya4Cc2yflJ7R68sQp8Jc3iJk1rJRK64B9rMP2qUI', 1),
(52, 'Ngoc@gmail.com', '12341234', 'Ngọc', '0773382145', '9h5Am1vO8ph5BSL92ZB87rXF8DA2', 'ex3io-tqQEi_KkLw3xNypy:APA91bFadPIqsVG4Wuoc2QVs7jK85QnzSBp91xO2LpUz-LQOcjK7zY9YqD3btsAUTqvEvESheD6qKy0LkcVw5tFfUUr7N9cvzfBtNhswAPyaiLCscbVxFWk', 0),
(53, 'Trandan1@gmail.com', '12345678', 'Nam', '0865063204', 'qcLc9MnXZQfqCciFKR8ZE7FZzHH2', 'ex3io-tqQEi_KkLw3xNypy:APA91bFadPIqsVG4Wuoc2QVs7jK85QnzSBp91xO2LpUz-LQOcjK7zY9YqD3btsAUTqvEvESheD6qKy0LkcVw5tFfUUr7N9cvzfBtNhswAPyaiLCscbVxFWk', 0),
(54, 'Onana@gmail.com', '12345678', 'ONANA', '0773321141', 'HALG7DWSwCO97n9DAIgmXUUhm472', 'ex3io-tqQEi_KkLw3xNypy:APA91bFadPIqsVG4Wuoc2QVs7jK85QnzSBp91xO2LpUz-LQOcjK7zY9YqD3btsAUTqvEvESheD6qKy0LkcVw5tFfUUr7N9cvzfBtNhswAPyaiLCscbVxFWk', 1),
(55, 'userNam@gmail.com', '12341234', 'NamBrithday', '0773382141', 'NZCchtco8gWlKUkl2a17crinwXj1', 'ex3io-tqQEi_KkLw3xNypy:APA91bFadPIqsVG4Wuoc2QVs7jK85QnzSBp91xO2LpUz-LQOcjK7zY9YqD3btsAUTqvEvESheD6qKy0LkcVw5tFfUUr7N9cvzfBtNhswAPyaiLCscbVxFWk', 0),
(56, 'baongoc@gmail.com', '12345678', 'Ngọc iu dấu', '0865063204', '7DbIraVFHYSEZI9KVAEUCXbVisa2', 'ex3io-tqQEi_KkLw3xNypy:APA91bFadPIqsVG4Wuoc2QVs7jK85QnzSBp91xO2LpUz-LQOcjK7zY9YqD3btsAUTqvEvESheD6qKy0LkcVw5tFfUUr7N9cvzfBtNhswAPyaiLCscbVxFWk', 0),
(57, 'user9@gmail.com', '12341234', 'Trần Dần', '0865063204', 'qDAZcxkf3ce0ct5ZsA37LOhxoHp1', 'eEzwYGGbT8es3AFjf9Szle:APA91bHP9KDSXxaBKEfA1E8-iqDhjpby2Auk_HmyKcd0glgBF-RRZztIrJlUXOfondk9L0WGxHl-4gaufP2NzbNaMoWue3rRaGpY-Q-dN160KiKDGTdJchs', 0);

--
-- Chỉ mục cho các bảng đã đổ
--

--
-- Chỉ mục cho bảng `donhang`
--
ALTER TABLE `donhang`
  ADD PRIMARY KEY (`id`);

--
-- Chỉ mục cho bảng `khuyenmai`
--
ALTER TABLE `khuyenmai`
  ADD PRIMARY KEY (`id`);

--
-- Chỉ mục cho bảng `sanpham`
--
ALTER TABLE `sanpham`
  ADD PRIMARY KEY (`id`);

--
-- Chỉ mục cho bảng `sanphammoi`
--
ALTER TABLE `sanphammoi`
  ADD PRIMARY KEY (`id`);

--
-- Chỉ mục cho bảng `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT cho các bảng đã đổ
--

--
-- AUTO_INCREMENT cho bảng `donhang`
--
ALTER TABLE `donhang`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=273;

--
-- AUTO_INCREMENT cho bảng `khuyenmai`
--
ALTER TABLE `khuyenmai`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;

--
-- AUTO_INCREMENT cho bảng `sanpham`
--
ALTER TABLE `sanpham`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;

--
-- AUTO_INCREMENT cho bảng `sanphammoi`
--
ALTER TABLE `sanphammoi`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=111;

--
-- AUTO_INCREMENT cho bảng `user`
--
ALTER TABLE `user`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=58;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
